// This file is autogenerated by mspm0-metapac-gen: do not edit by hand.

include!("../metadata_0035.rs");
pub static METADATA: Metadata = Metadata {
    name: "mspm0g3506pt",
    family: "mspm0g350x",
    peripherals: PERIPHERALS,
    pins: PINS,
    interrupts: INTERRUPTS,
    interrupt_groups: INTERRUPT_GROUPS,
    dma_channels: DMA_CHANNELS,
    adc_memctl: 12,
    adc_vrsel: 5,
};
