// This file is autogenerated by mspm0-metapac-gen: do not edit by hand.

include!("../metadata_0038.rs");
pub static METADATA: Metadata = Metadata {
    name: "mspm0l1227pt",
    family: "mspm0l122x",
    peripherals: PERIPHERALS,
    pins: PINS,
    interrupts: INTERRUPTS,
    dma_channels: DMA_CHANNELS,
};
