// This file is autogenerated by mspm0-metapac-gen: do not edit by hand.

include!("../metadata_0011.rs");
pub static METADATA: Metadata = Metadata {
    name: "mspm0g1505rge",
    family: "mspm0g150x",
    peripherals: PERIPHERALS,
    pins: PINS,
    interrupts: INTERRUPTS,
    dma_channels: DMA_CHANNELS,
};
