// This file is autogenerated by mspm0-metapac-gen: do not edit by hand.
#[cfg(feature = "rt")]
pub const NVIC_PRIO_BITS: u32 = 2;
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum Interrupt {
    GROUP0 = 0,
    GROUP1 = 1,
    TIMB0 = 2,
    ADC0 = 4,
    USBFS0 = 6,
    UC0 = 9,
    UC1 = 10,
    I2S0 = 11,
    NPU = 12,
    UC2 = 13,
    UC3 = 14,
    TIMG0 = 16,
    TIMG6 = 17,
    TIMA0 = 18,
    TIMG7 = 20,
    AESADV = 28,
    LFSS = 30,
    DMA = 31,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
#[repr(u8)]
pub enum Group0 {
    WWDT0 = 0,
    WWDT1 = 1,
    DEBUGSS = 2,
    FLASHCTL = 3,
    SYSCTL = 6,
}
impl TryFrom<u8> for Group0 {
    type Error = ();
    #[inline]
    fn try_from(value: u8) -> Result<Self, Self::Error> {
        match value {
            0 => Ok(Self::WWDT0),
            1 => Ok(Self::WWDT1),
            2 => Ok(Self::DEBUGSS),
            3 => Ok(Self::FLASHCTL),
            6 => Ok(Self::SYSCTL),
            _ => Err(()),
        }
    }
}
#[repr(u8)]
pub enum Group1 {
    GPIOA = 0,
    GPIOB = 1,
    COMP0 = 2,
}
impl TryFrom<u8> for Group1 {
    type Error = ();
    #[inline]
    fn try_from(value: u8) -> Result<Self, Self::Error> {
        match value {
            0 => Ok(Self::GPIOA),
            1 => Ok(Self::GPIOB),
            2 => Ok(Self::COMP0),
            _ => Err(()),
        }
    }
}
#[cfg(feature = "rt")]
mod _vectors {
    extern "C" {
        fn NonMaskableInt();
        fn HardFault();
        fn SVCall();
        fn PendSV();
        fn SysTick();
        fn GROUP0();
        fn GROUP1();
        fn TIMB0();
        fn ADC0();
        fn USBFS0();
        fn UC0();
        fn UC1();
        fn I2S0();
        fn NPU();
        fn UC2();
        fn UC3();
        fn TIMG0();
        fn TIMG6();
        fn TIMA0();
        fn TIMG7();
        fn AESADV();
        fn LFSS();
        fn DMA();
    }
    #[repr(C)]
    pub union Vector {
        _handler: unsafe extern "C" fn(),
        _reserved: u32,
    }
    #[link_section = ".vector_table.interrupts"]
    #[no_mangle]
    pub static __INTERRUPTS: [Vector; 32] = [
        Vector { _handler: GROUP0 },
        Vector { _handler: GROUP1 },
        Vector { _handler: TIMB0 },
        Vector { _reserved: 0 },
        Vector { _handler: ADC0 },
        Vector { _reserved: 0 },
        Vector { _handler: USBFS0 },
        Vector { _reserved: 0 },
        Vector { _reserved: 0 },
        Vector { _handler: UC0 },
        Vector { _handler: UC1 },
        Vector { _handler: I2S0 },
        Vector { _handler: NPU },
        Vector { _handler: UC2 },
        Vector { _handler: UC3 },
        Vector { _reserved: 0 },
        Vector { _handler: TIMG0 },
        Vector { _handler: TIMG6 },
        Vector { _handler: TIMA0 },
        Vector { _reserved: 0 },
        Vector { _handler: TIMG7 },
        Vector { _reserved: 0 },
        Vector { _reserved: 0 },
        Vector { _reserved: 0 },
        Vector { _reserved: 0 },
        Vector { _reserved: 0 },
        Vector { _reserved: 0 },
        Vector { _reserved: 0 },
        Vector { _handler: AESADV },
        Vector { _reserved: 0 },
        Vector { _handler: LFSS },
        Vector { _handler: DMA },
    ];
}
#[cfg(feature = "rt")]
pub use cortex_m_rt::interrupt;
#[cfg(feature = "rt")]
pub use Interrupt as interrupt;
#[path = "../../peripherals/adc_v1.rs"]
pub mod adc;
#[path = "../../peripherals/cpuss_v1.rs"]
pub mod cpuss;
#[path = "../../peripherals/dma_v1.rs"]
pub mod dma;
#[path = "../../peripherals/gpio_v1.rs"]
pub mod gpio;
#[path = "../../peripherals/iomux_v1.rs"]
pub mod iomux;
#[path = "../../peripherals/sysctl_g350x_g310x_g150x_g110x.rs"]
pub mod sysctl;
#[path = "../../peripherals/tim_v1.rs"]
pub mod tim;
#[path = "../../peripherals/wwdt_v1.rs"]
pub mod wwdt;
pub const ADC0: adc::Adc = unsafe { adc::Adc::from_ptr(1073758208 as *mut _) };
#[doc = "Address: 1078206464"]
pub const AESADV: () = ();
#[doc = "Address: 1073774592"]
pub const COMP0: () = ();
pub const CPUSS: cpuss::Cpuss = unsafe { cpuss::Cpuss::from_ptr(1077936128 as *mut _) };
#[doc = "Address: 1078198272"]
pub const CRCP0: () = ();
#[doc = "Address: 1074556928"]
pub const DEBUGSS: () = ();
pub const DMA: dma::Dma = unsafe { dma::Dma::from_ptr(1078108160 as *mut _) };
#[doc = "Address: 1074565120"]
pub const EVENT: () = ();
#[doc = "Address: 1074581504"]
pub const FLASHCTL: () = ();
pub const GPIOA: gpio::Gpio = unsafe { gpio::Gpio::from_ptr(1074397184 as *mut _) };
pub const GPIOB: gpio::Gpio = unsafe { gpio::Gpio::from_ptr(1074405376 as *mut _) };
#[doc = "Address: 1078439936"]
pub const I2S0: () = ();
pub const IOMUX: iomux::Iomux = unsafe { iomux::Iomux::from_ptr(1078099968 as *mut _) };
#[doc = "Address: 1074348032"]
pub const IWDT: () = ();
#[doc = "Address: 1074446336"]
pub const KEYSTORECTL: () = ();
#[doc = "Address: 1074348032"]
pub const LFSS: () = ();
#[doc = "Address: 1083174912"]
pub const NPU: () = ();
#[doc = "Address: 1074348032"]
pub const RTC_B: () = ();
#[doc = "Address: 1084878848"]
pub const SPG0: () = ();
pub const SYSCTL: sysctl::Sysctl = unsafe { sysctl::Sysctl::from_ptr(1074458624 as *mut _) };
pub const TIMA0: tim::Tim = unsafe { tim::Tim::from_ptr(1082523648 as *mut _) };
pub const TIMB0: tim::Tim = unsafe { tim::Tim::from_ptr(1074495488 as *mut _) };
pub const TIMG0: tim::Tim = unsafe { tim::Tim::from_ptr(1074282496 as *mut _) };
pub const TIMG6: tim::Tim = unsafe { tim::Tim::from_ptr(1082556416 as *mut _) };
pub const TIMG7: tim::Tim = unsafe { tim::Tim::from_ptr(1082564608 as *mut _) };
#[doc = "Address: 1084751872"]
pub const UC0: () = ();
#[doc = "Address: 1084760064"]
pub const UC1: () = ();
#[doc = "Address: 1085800448"]
pub const UC2: () = ();
#[doc = "Address: 1085808640"]
pub const UC3: () = ();
#[doc = "Address: 1078456320"]
pub const USBFS0: () = ();
#[doc = "Address: 1073938432"]
pub const VREF: () = ();
#[doc = "Address: 1078083584"]
pub const WUC: () = ();
pub const WWDT0: wwdt::Wwdt = unsafe { wwdt::Wwdt::from_ptr(1074266112 as *mut _) };
pub const WWDT1: wwdt::Wwdt = unsafe { wwdt::Wwdt::from_ptr(1074274304 as *mut _) };
