// This file is autogenerated by mspm0-metapac-gen: do not edit by hand.

include!("../metadata_0021.rs");
pub static METADATA: Metadata = Metadata {
    name: "mspm0g3507dgs28",
    family: "mspm0g350x",
    peripherals: PERIPHERALS,
    pins: PINS,
    interrupts: INTERRUPTS,
    dma_channels: DMA_CHANNELS,
};
