// This file is autogenerated by mspm0-metapac-gen: do not edit by hand.

include!("../metadata_0036.rs");
pub static METADATA: Metadata = Metadata {
    name: "mspm0g3519pz",
    family: "mspm0g351x",
    peripherals: PERIPHERALS,
    pins: PINS,
    interrupts: INTERRUPTS,
    interrupt_groups: INTERRUPT_GROUPS,
    dma_channels: DMA_CHANNELS,
    adc_memctl: 24,
    adc_vrsel: 5,
};
