// This file is autogenerated by mspm0-metapac-gen: do not edit by hand.

include!("../metadata_0047.rs");
pub static METADATA: Metadata = Metadata {
    name: "mspm0l1343dgs20",
    family: "mspm0l134x",
    peripherals: PERIPHERALS,
    pins: PINS,
    interrupts: INTERRUPTS,
    interrupt_groups: INTERRUPT_GROUPS,
    dma_channels: DMA_CHANNELS,
    adc_memctl: 4,
    adc_vrsel: 5,
};
