// This file is autogenerated by mspm0-metapac-gen: do not edit by hand.

include!("../metadata_0037.rs");
pub static METADATA: Metadata = Metadata {
    name: "mspm0l1228pn",
    family: "mspm0l122x",
    peripherals: PERIPHERALS,
    pins: PINS,
    interrupts: INTERRUPTS,
    interrupt_groups: INTERRUPT_GROUPS,
    dma_channels: DMA_CHANNELS,
};
