// This file is autogenerated by mspm0-metapac-gen: do not edit by hand.

include!("../metadata_0018.rs");
pub static METADATA: Metadata = Metadata {
    name: "mspm0g3107dgs20",
    family: "mspm0g310x",
    peripherals: PERIPHERALS,
    pins: PINS,
    interrupts: INTERRUPTS,
    dma_channels: DMA_CHANNELS,
};
