// This file is autogenerated by mspm0-metapac-gen: do not edit by hand.

include!("../metadata_0060.rs");
pub static METADATA: Metadata = Metadata {
    name: "mspm0l1126ruy",
    family: "mspm0l112x",
    peripherals: PERIPHERALS,
    pins: PINS,
    interrupts: INTERRUPTS,
    interrupt_groups: INTERRUPT_GROUPS,
    dma_channels: DMA_CHANNELS,
    adc_memctl: 12,
    adc_vrsel: 5,
};
