// This file is autogenerated by mspm0-metapac-gen: do not edit by hand.
#![allow(clippy::missing_safety_doc)]
#![allow(clippy::identity_op)]
#![allow(clippy::unnecessary_cast)]
#![allow(clippy::erasing_op)]
#[derive(Copy, Clone, Eq, PartialEq)]
pub struct Chan {
    ptr: *mut u8,
}
unsafe impl Send for Chan {}
unsafe impl Sync for Chan {}
impl Chan {
    #[inline(always)]
    pub const unsafe fn from_ptr(ptr: *mut ()) -> Self {
        Self { ptr: ptr as _ }
    }
    #[inline(always)]
    pub const fn as_ptr(&self) -> *mut () {
        self.ptr as _
    }
    ///DMA Channel Control.
    #[inline(always)]
    pub const fn ctl(self) -> crate::common::Reg<regs::Ctl, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x0usize) as _) }
    }
    ///DMA Channel Source Address.
    #[inline(always)]
    pub const fn sa(self) -> crate::common::Reg<u32, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x04usize) as _) }
    }
    ///DMA Channel Destination Address.
    #[inline(always)]
    pub const fn da(self) -> crate::common::Reg<u32, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x08usize) as _) }
    }
    ///DMA Channel Size.
    #[inline(always)]
    pub const fn sz(self) -> crate::common::Reg<regs::Sz, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x0cusize) as _) }
    }
}
///PERIPHERALREGION.
#[derive(Copy, Clone, Eq, PartialEq)]
pub struct Dma {
    ptr: *mut u8,
}
unsafe impl Send for Dma {}
unsafe impl Sync for Dma {}
impl Dma {
    #[inline(always)]
    pub const unsafe fn from_ptr(ptr: *mut ()) -> Self {
        Self { ptr: ptr as _ }
    }
    #[inline(always)]
    pub const fn as_ptr(&self) -> *mut () {
        self.ptr as _
    }
    ///Subscriber Port 0.
    #[inline(always)]
    pub const fn fsub(
        self,
        n: usize,
    ) -> crate::common::Reg<regs::Fport, crate::common::RW> {
        assert!(n < 2usize);
        unsafe {
            crate::common::Reg::from_ptr(
                self.ptr.wrapping_add(0x0400usize + n * 4usize) as _,
            )
        }
    }
    ///Publisher Port 0.
    #[inline(always)]
    pub const fn fpub(
        self,
        n: usize,
    ) -> crate::common::Reg<regs::Fport, crate::common::RW> {
        assert!(n < 1usize);
        unsafe {
            crate::common::Reg::from_ptr(
                self.ptr.wrapping_add(0x0444usize + n * 0usize) as _,
            )
        }
    }
    ///Peripheral Debug Control.
    #[inline(always)]
    pub const fn pdbgctl(self) -> crate::common::Reg<regs::Pdbgctl, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x1018usize) as _) }
    }
    #[inline(always)]
    pub const fn int_event(self, n: usize) -> IntEvent {
        assert!(n < 2usize);
        unsafe {
            IntEvent::from_ptr(self.ptr.wrapping_add(0x1020usize + n * 44usize) as _)
        }
    }
    ///Event Mode.
    #[inline(always)]
    pub const fn evt_mode(self) -> crate::common::Reg<regs::EvtMode, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x10e0usize) as _) }
    }
    ///Module Description.
    #[inline(always)]
    pub const fn desc(self) -> crate::common::Reg<regs::Desc, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x10fcusize) as _) }
    }
    ///DMA Channel Priority Control.
    #[inline(always)]
    pub const fn prio(self) -> crate::common::Reg<regs::Prio, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x1100usize) as _) }
    }
    #[inline(always)]
    pub const fn trig(self, n: usize) -> Trig {
        assert!(n < 7usize);
        unsafe { Trig::from_ptr(self.ptr.wrapping_add(0x1110usize + n * 4usize) as _) }
    }
    #[inline(always)]
    pub const fn chan(self, n: usize) -> Chan {
        assert!(n < 7usize);
        unsafe { Chan::from_ptr(self.ptr.wrapping_add(0x1200usize + n * 16usize) as _) }
    }
}
#[derive(Copy, Clone, Eq, PartialEq)]
pub struct IntEvent {
    ptr: *mut u8,
}
unsafe impl Send for IntEvent {}
unsafe impl Sync for IntEvent {}
impl IntEvent {
    #[inline(always)]
    pub const unsafe fn from_ptr(ptr: *mut ()) -> Self {
        Self { ptr: ptr as _ }
    }
    #[inline(always)]
    pub const fn as_ptr(&self) -> *mut () {
        self.ptr as _
    }
    ///Interrupt index.
    #[inline(always)]
    pub const fn iidx(self) -> crate::common::Reg<regs::Iidx, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x0usize) as _) }
    }
    ///Interrupt mask.
    #[inline(always)]
    pub const fn imask(self) -> crate::common::Reg<regs::Int, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x08usize) as _) }
    }
    ///Raw interrupt status.
    #[inline(always)]
    pub const fn ris(self) -> crate::common::Reg<regs::Int, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x10usize) as _) }
    }
    ///Masked interrupt status.
    #[inline(always)]
    pub const fn mis(self) -> crate::common::Reg<regs::Int, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x18usize) as _) }
    }
    ///Interrupt set.
    #[inline(always)]
    pub const fn iset(self) -> crate::common::Reg<regs::Int, crate::common::W> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x20usize) as _) }
    }
    ///Interrupt clear.
    #[inline(always)]
    pub const fn iclr(self) -> crate::common::Reg<regs::Int, crate::common::W> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x28usize) as _) }
    }
}
#[derive(Copy, Clone, Eq, PartialEq)]
pub struct Trig {
    ptr: *mut u8,
}
unsafe impl Send for Trig {}
unsafe impl Sync for Trig {}
impl Trig {
    #[inline(always)]
    pub const unsafe fn from_ptr(ptr: *mut ()) -> Self {
        Self { ptr: ptr as _ }
    }
    #[inline(always)]
    pub const fn as_ptr(&self) -> *mut () {
        self.ptr as _
    }
    ///DMA Trigger Select.
    #[inline(always)]
    pub const fn tctl(self) -> crate::common::Reg<regs::Tctl, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x0usize) as _) }
    }
}
pub mod regs {
    ///DMA Channel Control.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Ctl(pub u32);
    impl Ctl {
        ///DMA request. Software-controlled DMA start. DMAREQ is reset automatically.
        #[must_use]
        #[inline(always)]
        pub const fn req(&self) -> bool {
            let val = (self.0 >> 0usize) & 0x01;
            val != 0
        }
        ///DMA request. Software-controlled DMA start. DMAREQ is reset automatically.
        #[inline(always)]
        pub const fn set_req(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize);
        }
        ///DMA enable.
        #[must_use]
        #[inline(always)]
        pub const fn en(&self) -> bool {
            let val = (self.0 >> 1usize) & 0x01;
            val != 0
        }
        ///DMA enable.
        #[inline(always)]
        pub const fn set_en(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize);
        }
        ///Automatic DMA channel enable on SA, DA, SZ register write. If channel is configured as SW trigger (TCTL=0), the AUTOEN will set the EN and REQ. If channel is configured as HW trigger (CTL!=0), the AUTOEN will only set the EN. Note: This feature is not present in all devices. Consult the device specific datasheet.
        #[must_use]
        #[inline(always)]
        pub const fn autoen(&self) -> super::vals::Autoen {
            let val = (self.0 >> 2usize) & 0x03;
            super::vals::Autoen::from_bits(val as u8)
        }
        ///Automatic DMA channel enable on SA, DA, SZ register write. If channel is configured as SW trigger (TCTL=0), the AUTOEN will set the EN and REQ. If channel is configured as HW trigger (CTL!=0), the AUTOEN will only set the EN. Note: This feature is not present in all devices. Consult the device specific datasheet.
        #[inline(always)]
        pub const fn set_autoen(&mut self, val: super::vals::Autoen) {
            self.0 = (self.0 & !(0x03 << 2usize))
                | (((val.to_bits() as u32) & 0x03) << 2usize);
        }
        ///Enable an early IRQ event. This can help software to react quicker to and DMA done event or allows some additional configuration before the channel is complete. Note: This register is only available in a FULL-channel configuration. Please consult the datasheet of the specific device to map which channel number has FULL or BASIC capability. In a BASIC configuration this register is a read only value and always reads as 0x0.
        #[must_use]
        #[inline(always)]
        pub const fn preirq(&self) -> super::vals::Preirq {
            let val = (self.0 >> 4usize) & 0x07;
            super::vals::Preirq::from_bits(val as u8)
        }
        ///Enable an early IRQ event. This can help software to react quicker to and DMA done event or allows some additional configuration before the channel is complete. Note: This register is only available in a FULL-channel configuration. Please consult the datasheet of the specific device to map which channel number has FULL or BASIC capability. In a BASIC configuration this register is a read only value and always reads as 0x0.
        #[inline(always)]
        pub const fn set_preirq(&mut self, val: super::vals::Preirq) {
            self.0 = (self.0 & !(0x07 << 4usize))
                | (((val.to_bits() as u32) & 0x07) << 4usize);
        }
        ///DMA source width. This bit selects the source data width as a byte, half word, word or long word.
        #[must_use]
        #[inline(always)]
        pub const fn srcwdth(&self) -> super::vals::Wdth {
            let val = (self.0 >> 8usize) & 0x03;
            super::vals::Wdth::from_bits(val as u8)
        }
        ///DMA source width. This bit selects the source data width as a byte, half word, word or long word.
        #[inline(always)]
        pub const fn set_srcwdth(&mut self, val: super::vals::Wdth) {
            self.0 = (self.0 & !(0x03 << 8usize))
                | (((val.to_bits() as u32) & 0x03) << 8usize);
        }
        ///DMA destination width. This bit selects the destination as a byte, half word, word or long word.
        #[must_use]
        #[inline(always)]
        pub const fn dstwdth(&self) -> super::vals::Wdth {
            let val = (self.0 >> 12usize) & 0x03;
            super::vals::Wdth::from_bits(val as u8)
        }
        ///DMA destination width. This bit selects the destination as a byte, half word, word or long word.
        #[inline(always)]
        pub const fn set_dstwdth(&mut self, val: super::vals::Wdth) {
            self.0 = (self.0 & !(0x03 << 12usize))
                | (((val.to_bits() as u32) & 0x03) << 12usize);
        }
        ///DMA source increment. This bit selects automatic incrementing or decrementing of the source address DMASA for each transfer. The amount of change to the DMASA is based on the definitin in the DMASRCWDTH. For example an increment of 1 (+1) on a WORD transfer will increment the DMASA by 4.
        #[must_use]
        #[inline(always)]
        pub const fn srcincr(&self) -> super::vals::Incr {
            let val = (self.0 >> 16usize) & 0x0f;
            super::vals::Incr::from_bits(val as u8)
        }
        ///DMA source increment. This bit selects automatic incrementing or decrementing of the source address DMASA for each transfer. The amount of change to the DMASA is based on the definitin in the DMASRCWDTH. For example an increment of 1 (+1) on a WORD transfer will increment the DMASA by 4.
        #[inline(always)]
        pub const fn set_srcincr(&mut self, val: super::vals::Incr) {
            self.0 = (self.0 & !(0x0f << 16usize))
                | (((val.to_bits() as u32) & 0x0f) << 16usize);
        }
        ///DMA destination increment. This bit selects automatic incrementing or decrementing of the destination address DMADA for each transfer. The amount of change to the DMADA is based on the definitin in the DMADSTWDTH. For example an increment of 1 (+1) on a WORD transfer will increment the DMADA by 4.
        #[must_use]
        #[inline(always)]
        pub const fn dstincr(&self) -> super::vals::Incr {
            let val = (self.0 >> 20usize) & 0x0f;
            super::vals::Incr::from_bits(val as u8)
        }
        ///DMA destination increment. This bit selects automatic incrementing or decrementing of the destination address DMADA for each transfer. The amount of change to the DMADA is based on the definitin in the DMADSTWDTH. For example an increment of 1 (+1) on a WORD transfer will increment the DMADA by 4.
        #[inline(always)]
        pub const fn set_dstincr(&mut self, val: super::vals::Incr) {
            self.0 = (self.0 & !(0x0f << 20usize))
                | (((val.to_bits() as u32) & 0x0f) << 20usize);
        }
        ///DMA extended mode Note: The extended transfer modes are only available in a FULL-channel configuration. Please consult the datasheet of the specific device to map which channel number has FULL or BASIC capability. In a BASIC channel configuration this register is a read-only register and reads 0x0.
        #[must_use]
        #[inline(always)]
        pub const fn em(&self) -> super::vals::Em {
            let val = (self.0 >> 24usize) & 0x03;
            super::vals::Em::from_bits(val as u8)
        }
        ///DMA extended mode Note: The extended transfer modes are only available in a FULL-channel configuration. Please consult the datasheet of the specific device to map which channel number has FULL or BASIC capability. In a BASIC channel configuration this register is a read-only register and reads 0x0.
        #[inline(always)]
        pub const fn set_em(&mut self, val: super::vals::Em) {
            self.0 = (self.0 & !(0x03 << 24usize))
                | (((val.to_bits() as u32) & 0x03) << 24usize);
        }
        ///DMA transfer mode register Note: The repeat-single (2h) and repeat-block (3h) transfer are only available in a FULL-channel configuration. Please consult the datasheet of the specific device to map which channel number has FULL or BASIC capability. In a BASIC channel configuration only the values for single (0h) and block (1h) transfer can be set.
        #[must_use]
        #[inline(always)]
        pub const fn tm(&self) -> super::vals::Tm {
            let val = (self.0 >> 28usize) & 0x03;
            super::vals::Tm::from_bits(val as u8)
        }
        ///DMA transfer mode register Note: The repeat-single (2h) and repeat-block (3h) transfer are only available in a FULL-channel configuration. Please consult the datasheet of the specific device to map which channel number has FULL or BASIC capability. In a BASIC channel configuration only the values for single (0h) and block (1h) transfer can be set.
        #[inline(always)]
        pub const fn set_tm(&mut self, val: super::vals::Tm) {
            self.0 = (self.0 & !(0x03 << 28usize))
                | (((val.to_bits() as u32) & 0x03) << 28usize);
        }
    }
    impl Default for Ctl {
        #[inline(always)]
        fn default() -> Ctl {
            Ctl(0)
        }
    }
    impl core::fmt::Debug for Ctl {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Ctl")
                .field("req", &self.req())
                .field("en", &self.en())
                .field("autoen", &self.autoen())
                .field("preirq", &self.preirq())
                .field("srcwdth", &self.srcwdth())
                .field("dstwdth", &self.dstwdth())
                .field("srcincr", &self.srcincr())
                .field("dstincr", &self.dstincr())
                .field("em", &self.em())
                .field("tm", &self.tm())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Ctl {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f,
                "Ctl {{ req: {=bool:?}, en: {=bool:?}, autoen: {:?}, preirq: {:?}, srcwdth: {:?}, dstwdth: {:?}, srcincr: {:?}, dstincr: {:?}, em: {:?}, tm: {:?} }}",
                self.req(), self.en(), self.autoen(), self.preirq(), self.srcwdth(), self
                .dstwdth(), self.srcincr(), self.dstincr(), self.em(), self.tm()
            )
        }
    }
    ///Module Description.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Desc(pub u32);
    impl Desc {
        ///Minor rev of the IP.
        #[must_use]
        #[inline(always)]
        pub const fn minrev(&self) -> u8 {
            let val = (self.0 >> 0usize) & 0x0f;
            val as u8
        }
        ///Minor rev of the IP.
        #[inline(always)]
        pub const fn set_minrev(&mut self, val: u8) {
            self.0 = (self.0 & !(0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize);
        }
        ///Major rev of the IP.
        #[must_use]
        #[inline(always)]
        pub const fn majrev(&self) -> u8 {
            let val = (self.0 >> 4usize) & 0x0f;
            val as u8
        }
        ///Major rev of the IP.
        #[inline(always)]
        pub const fn set_majrev(&mut self, val: u8) {
            self.0 = (self.0 & !(0x0f << 4usize)) | (((val as u32) & 0x0f) << 4usize);
        }
        ///Feature Set for the DMA: number of DMA channel minus one (e.g. 0->1ch, 2->3ch, 15->16ch).
        #[must_use]
        #[inline(always)]
        pub const fn featurever(&self) -> u8 {
            let val = (self.0 >> 12usize) & 0x0f;
            val as u8
        }
        ///Feature Set for the DMA: number of DMA channel minus one (e.g. 0->1ch, 2->3ch, 15->16ch).
        #[inline(always)]
        pub const fn set_featurever(&mut self, val: u8) {
            self.0 = (self.0 & !(0x0f << 12usize)) | (((val as u32) & 0x0f) << 12usize);
        }
        ///Module identification contains a unique peripheral identification number. The assignments are maintained in a central database for all of the platform modules to ensure uniqueness.
        #[must_use]
        #[inline(always)]
        pub const fn moduleid(&self) -> u16 {
            let val = (self.0 >> 16usize) & 0xffff;
            val as u16
        }
        ///Module identification contains a unique peripheral identification number. The assignments are maintained in a central database for all of the platform modules to ensure uniqueness.
        #[inline(always)]
        pub const fn set_moduleid(&mut self, val: u16) {
            self.0 = (self.0 & !(0xffff << 16usize))
                | (((val as u32) & 0xffff) << 16usize);
        }
    }
    impl Default for Desc {
        #[inline(always)]
        fn default() -> Desc {
            Desc(0)
        }
    }
    impl core::fmt::Debug for Desc {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Desc")
                .field("minrev", &self.minrev())
                .field("majrev", &self.majrev())
                .field("featurever", &self.featurever())
                .field("moduleid", &self.moduleid())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Desc {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f,
                "Desc {{ minrev: {=u8:?}, majrev: {=u8:?}, featurever: {=u8:?}, moduleid: {=u16:?} }}",
                self.minrev(), self.majrev(), self.featurever(), self.moduleid()
            )
        }
    }
    ///Event Mode.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct EvtMode(pub u32);
    impl EvtMode {
        ///Event line mode select for event corresponding to interrupt event INT_EVENT\[0\].
        #[must_use]
        #[inline(always)]
        pub const fn cpu(&self) -> super::vals::EvtCfg {
            let val = (self.0 >> 0usize) & 0x03;
            super::vals::EvtCfg::from_bits(val as u8)
        }
        ///Event line mode select for event corresponding to interrupt event INT_EVENT\[0\].
        #[inline(always)]
        pub const fn set_cpu(&mut self, val: super::vals::EvtCfg) {
            self.0 = (self.0 & !(0x03 << 0usize))
                | (((val.to_bits() as u32) & 0x03) << 0usize);
        }
        ///Event line mode select for event corresponding to generic event INT_EVENT\[1\].
        #[must_use]
        #[inline(always)]
        pub const fn event(&self) -> super::vals::EvtCfg {
            let val = (self.0 >> 2usize) & 0x03;
            super::vals::EvtCfg::from_bits(val as u8)
        }
        ///Event line mode select for event corresponding to generic event INT_EVENT\[1\].
        #[inline(always)]
        pub const fn set_event(&mut self, val: super::vals::EvtCfg) {
            self.0 = (self.0 & !(0x03 << 2usize))
                | (((val.to_bits() as u32) & 0x03) << 2usize);
        }
    }
    impl Default for EvtMode {
        #[inline(always)]
        fn default() -> EvtMode {
            EvtMode(0)
        }
    }
    impl core::fmt::Debug for EvtMode {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("EvtMode")
                .field("cpu", &self.cpu())
                .field("event", &self.event())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for EvtMode {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f, "EvtMode {{ cpu: {:?}, event: {:?} }}", self.cpu(), self.event()
            )
        }
    }
    ///Publisher Port 0.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Fport(pub u32);
    impl Fport {
        ///0 = disconnected. 1-255 = connected to channelID = CHANID.
        #[must_use]
        #[inline(always)]
        pub const fn chanid(&self) -> u8 {
            let val = (self.0 >> 0usize) & 0x0f;
            val as u8
        }
        ///0 = disconnected. 1-255 = connected to channelID = CHANID.
        #[inline(always)]
        pub const fn set_chanid(&mut self, val: u8) {
            self.0 = (self.0 & !(0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize);
        }
    }
    impl Default for Fport {
        #[inline(always)]
        fn default() -> Fport {
            Fport(0)
        }
    }
    impl core::fmt::Debug for Fport {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Fport").field("chanid", &self.chanid()).finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Fport {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(f, "Fport {{ chanid: {=u8:?} }}", self.chanid())
        }
    }
    ///Interrupt index.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Iidx(pub u32);
    impl Iidx {
        ///Interrupt index status.
        #[must_use]
        #[inline(always)]
        pub const fn stat(&self) -> super::vals::Stat {
            let val = (self.0 >> 0usize) & 0xff;
            super::vals::Stat::from_bits(val as u8)
        }
        ///Interrupt index status.
        #[inline(always)]
        pub const fn set_stat(&mut self, val: super::vals::Stat) {
            self.0 = (self.0 & !(0xff << 0usize))
                | (((val.to_bits() as u32) & 0xff) << 0usize);
        }
    }
    impl Default for Iidx {
        #[inline(always)]
        fn default() -> Iidx {
            Iidx(0)
        }
    }
    impl core::fmt::Debug for Iidx {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Iidx").field("stat", &self.stat()).finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Iidx {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(f, "Iidx {{ stat: {:?} }}", self.stat())
        }
    }
    ///Interrupt clear.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Int(pub u32);
    impl Int {
        ///DMA Channel 0 interrupt signals that size counter reached zero (DMASZ=0).
        #[must_use]
        #[inline(always)]
        pub const fn ch(&self, n: usize) -> bool {
            assert!(n < 16usize);
            let offs = 0usize + n * 1usize;
            let val = (self.0 >> offs) & 0x01;
            val != 0
        }
        ///DMA Channel 0 interrupt signals that size counter reached zero (DMASZ=0).
        #[inline(always)]
        pub const fn set_ch(&mut self, n: usize, val: bool) {
            assert!(n < 16usize);
            let offs = 0usize + n * 1usize;
            self.0 = (self.0 & !(0x01 << offs)) | (((val as u32) & 0x01) << offs);
        }
        ///Pre-IRQ for Channel 0. Size counter reached Pre-IRQ threshold.
        #[must_use]
        #[inline(always)]
        pub const fn preirqch(&self, n: usize) -> bool {
            assert!(n < 8usize);
            let offs = 16usize + n * 1usize;
            let val = (self.0 >> offs) & 0x01;
            val != 0
        }
        ///Pre-IRQ for Channel 0. Size counter reached Pre-IRQ threshold.
        #[inline(always)]
        pub const fn set_preirqch(&mut self, n: usize, val: bool) {
            assert!(n < 8usize);
            let offs = 16usize + n * 1usize;
            self.0 = (self.0 & !(0x01 << offs)) | (((val as u32) & 0x01) << offs);
        }
        ///DMA address error, SRC address not reachable.
        #[must_use]
        #[inline(always)]
        pub const fn addrerr(&self) -> bool {
            let val = (self.0 >> 24usize) & 0x01;
            val != 0
        }
        ///DMA address error, SRC address not reachable.
        #[inline(always)]
        pub const fn set_addrerr(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 24usize)) | (((val as u32) & 0x01) << 24usize);
        }
        ///DMA data error, SRC data might be corrupted (PAR or ECC error).
        #[must_use]
        #[inline(always)]
        pub const fn dataerr(&self) -> bool {
            let val = (self.0 >> 25usize) & 0x01;
            val != 0
        }
        ///DMA data error, SRC data might be corrupted (PAR or ECC error).
        #[inline(always)]
        pub const fn set_dataerr(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 25usize)) | (((val as u32) & 0x01) << 25usize);
        }
    }
    impl Default for Int {
        #[inline(always)]
        fn default() -> Int {
            Int(0)
        }
    }
    impl core::fmt::Debug for Int {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Int")
                .field("ch[0]", &self.ch(0usize))
                .field("ch[1]", &self.ch(1usize))
                .field("ch[2]", &self.ch(2usize))
                .field("ch[3]", &self.ch(3usize))
                .field("ch[4]", &self.ch(4usize))
                .field("ch[5]", &self.ch(5usize))
                .field("ch[6]", &self.ch(6usize))
                .field("ch[7]", &self.ch(7usize))
                .field("ch[8]", &self.ch(8usize))
                .field("ch[9]", &self.ch(9usize))
                .field("ch[10]", &self.ch(10usize))
                .field("ch[11]", &self.ch(11usize))
                .field("ch[12]", &self.ch(12usize))
                .field("ch[13]", &self.ch(13usize))
                .field("ch[14]", &self.ch(14usize))
                .field("ch[15]", &self.ch(15usize))
                .field("preirqch[0]", &self.preirqch(0usize))
                .field("preirqch[1]", &self.preirqch(1usize))
                .field("preirqch[2]", &self.preirqch(2usize))
                .field("preirqch[3]", &self.preirqch(3usize))
                .field("preirqch[4]", &self.preirqch(4usize))
                .field("preirqch[5]", &self.preirqch(5usize))
                .field("preirqch[6]", &self.preirqch(6usize))
                .field("preirqch[7]", &self.preirqch(7usize))
                .field("addrerr", &self.addrerr())
                .field("dataerr", &self.dataerr())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Int {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f,
                "Int {{ ch[0]: {=bool:?}, ch[1]: {=bool:?}, ch[2]: {=bool:?}, ch[3]: {=bool:?}, ch[4]: {=bool:?}, ch[5]: {=bool:?}, ch[6]: {=bool:?}, ch[7]: {=bool:?}, ch[8]: {=bool:?}, ch[9]: {=bool:?}, ch[10]: {=bool:?}, ch[11]: {=bool:?}, ch[12]: {=bool:?}, ch[13]: {=bool:?}, ch[14]: {=bool:?}, ch[15]: {=bool:?}, preirqch[0]: {=bool:?}, preirqch[1]: {=bool:?}, preirqch[2]: {=bool:?}, preirqch[3]: {=bool:?}, preirqch[4]: {=bool:?}, preirqch[5]: {=bool:?}, preirqch[6]: {=bool:?}, preirqch[7]: {=bool:?}, addrerr: {=bool:?}, dataerr: {=bool:?} }}",
                self.ch(0usize), self.ch(1usize), self.ch(2usize), self.ch(3usize), self
                .ch(4usize), self.ch(5usize), self.ch(6usize), self.ch(7usize), self
                .ch(8usize), self.ch(9usize), self.ch(10usize), self.ch(11usize), self
                .ch(12usize), self.ch(13usize), self.ch(14usize), self.ch(15usize), self
                .preirqch(0usize), self.preirqch(1usize), self.preirqch(2usize), self
                .preirqch(3usize), self.preirqch(4usize), self.preirqch(5usize), self
                .preirqch(6usize), self.preirqch(7usize), self.addrerr(), self.dataerr()
            )
        }
    }
    ///Peripheral Debug Control.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Pdbgctl(pub u32);
    impl Pdbgctl {
        ///Free run control.
        #[must_use]
        #[inline(always)]
        pub const fn free(&self) -> bool {
            let val = (self.0 >> 0usize) & 0x01;
            val != 0
        }
        ///Free run control.
        #[inline(always)]
        pub const fn set_free(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize);
        }
        /**Soft halt boundary control. This function is only available, if \[FREE\]
is set to 'STOP'.*/
        #[must_use]
        #[inline(always)]
        pub const fn soft(&self) -> super::vals::Soft {
            let val = (self.0 >> 1usize) & 0x01;
            super::vals::Soft::from_bits(val as u8)
        }
        /**Soft halt boundary control. This function is only available, if \[FREE\]
is set to 'STOP'.*/
        #[inline(always)]
        pub const fn set_soft(&mut self, val: super::vals::Soft) {
            self.0 = (self.0 & !(0x01 << 1usize))
                | (((val.to_bits() as u32) & 0x01) << 1usize);
        }
    }
    impl Default for Pdbgctl {
        #[inline(always)]
        fn default() -> Pdbgctl {
            Pdbgctl(0)
        }
    }
    impl core::fmt::Debug for Pdbgctl {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Pdbgctl")
                .field("free", &self.free())
                .field("soft", &self.soft())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Pdbgctl {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f, "Pdbgctl {{ free: {=bool:?}, soft: {:?} }}", self.free(), self.soft()
            )
        }
    }
    ///DMA Channel Priority Control.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Prio(pub u32);
    impl Prio {
        ///Round robin. This bit enables the round-robin DMA channel priorities.
        #[must_use]
        #[inline(always)]
        pub const fn roundrobin(&self) -> bool {
            let val = (self.0 >> 0usize) & 0x01;
            val != 0
        }
        ///Round robin. This bit enables the round-robin DMA channel priorities.
        #[inline(always)]
        pub const fn set_roundrobin(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize);
        }
        ///Define the burst size of a block transfer, before the priority is re-evaluated.
        #[must_use]
        #[inline(always)]
        pub const fn burstsz(&self) -> super::vals::Burstsz {
            let val = (self.0 >> 16usize) & 0x03;
            super::vals::Burstsz::from_bits(val as u8)
        }
        ///Define the burst size of a block transfer, before the priority is re-evaluated.
        #[inline(always)]
        pub const fn set_burstsz(&mut self, val: super::vals::Burstsz) {
            self.0 = (self.0 & !(0x03 << 16usize))
                | (((val.to_bits() as u32) & 0x03) << 16usize);
        }
    }
    impl Default for Prio {
        #[inline(always)]
        fn default() -> Prio {
            Prio(0)
        }
    }
    impl core::fmt::Debug for Prio {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Prio")
                .field("roundrobin", &self.roundrobin())
                .field("burstsz", &self.burstsz())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Prio {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f, "Prio {{ roundrobin: {=bool:?}, burstsz: {:?} }}", self.roundrobin(),
                self.burstsz()
            )
        }
    }
    ///DMA Channel Size.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Sz(pub u32);
    impl Sz {
        ///DMA Channel Size in number of transfers.
        #[must_use]
        #[inline(always)]
        pub const fn size(&self) -> u16 {
            let val = (self.0 >> 0usize) & 0xffff;
            val as u16
        }
        ///DMA Channel Size in number of transfers.
        #[inline(always)]
        pub const fn set_size(&mut self, val: u16) {
            self.0 = (self.0 & !(0xffff << 0usize))
                | (((val as u32) & 0xffff) << 0usize);
        }
    }
    impl Default for Sz {
        #[inline(always)]
        fn default() -> Sz {
            Sz(0)
        }
    }
    impl core::fmt::Debug for Sz {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Sz").field("size", &self.size()).finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Sz {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(f, "Sz {{ size: {=u16:?} }}", self.size())
        }
    }
    ///DMA Trigger Select.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Tctl(pub u32);
    impl Tctl {
        ///DMA Trigger Select Note: Reference the datasheet of the device to see the specific trigger mapping.
        #[must_use]
        #[inline(always)]
        pub const fn tsel(&self) -> u8 {
            let val = (self.0 >> 0usize) & 0x3f;
            val as u8
        }
        ///DMA Trigger Select Note: Reference the datasheet of the device to see the specific trigger mapping.
        #[inline(always)]
        pub const fn set_tsel(&mut self, val: u8) {
            self.0 = (self.0 & !(0x3f << 0usize)) | (((val as u32) & 0x3f) << 0usize);
        }
        ///DMA Trigger by Internal Channel.
        #[must_use]
        #[inline(always)]
        pub const fn tint(&self) -> super::vals::Tint {
            let val = (self.0 >> 7usize) & 0x01;
            super::vals::Tint::from_bits(val as u8)
        }
        ///DMA Trigger by Internal Channel.
        #[inline(always)]
        pub const fn set_tint(&mut self, val: super::vals::Tint) {
            self.0 = (self.0 & !(0x01 << 7usize))
                | (((val.to_bits() as u32) & 0x01) << 7usize);
        }
    }
    impl Default for Tctl {
        #[inline(always)]
        fn default() -> Tctl {
            Tctl(0)
        }
    }
    impl core::fmt::Debug for Tctl {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Tctl")
                .field("tsel", &self.tsel())
                .field("tint", &self.tint())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Tctl {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f, "Tctl {{ tsel: {=u8:?}, tint: {:?} }}", self.tsel(), self.tint()
            )
        }
    }
}
pub mod vals {
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum Autoen {
        ///No automatic DMA enable
        None = 0x0,
        ///Automatic DMA channel enable on SA register write.
        Sa = 0x01,
        ///Automatic DMA channel enable on DA register write.
        Da = 0x02,
        ///Automatic DMA channel enable on SZ register write.
        Sz = 0x03,
    }
    impl Autoen {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Autoen {
            unsafe { core::mem::transmute(val & 0x03) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Autoen {
        #[inline(always)]
        fn from(val: u8) -> Autoen {
            Autoen::from_bits(val)
        }
    }
    impl From<Autoen> for u8 {
        #[inline(always)]
        fn from(val: Autoen) -> u8 {
            Autoen::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum Burstsz {
        ///There is no burst size, the whole block transfer is completed on one transfer without interruption.
        Infiniti = 0x0,
        ///The burst size is 8, after 8 transfers the block transfer is interrupted and the priority is reevaluated.
        Burst8 = 0x01,
        ///The burst size is 16, after 16 transfers the block transfer is interrupted and the priority is reevaluated.
        Burst16 = 0x02,
        ///The burst size is 32, after 32 transfers the block transfer is interrupted and the priority is reevaluated.
        Burst32 = 0x03,
    }
    impl Burstsz {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Burstsz {
            unsafe { core::mem::transmute(val & 0x03) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Burstsz {
        #[inline(always)]
        fn from(val: u8) -> Burstsz {
            Burstsz::from_bits(val)
        }
    }
    impl From<Burstsz> for u8 {
        #[inline(always)]
        fn from(val: Burstsz) -> u8 {
            Burstsz::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum Em {
        ///Normal mode is related to transfers from SRC to DST.
        Normal = 0x0,
        _RESERVED_1 = 0x01,
        ///Fill mode will copy the SA register content as data to DA.
        Fillmode = 0x02,
        ///Table mode will read an address and data value from SA and write the data to address.
        Tablemode = 0x03,
    }
    impl Em {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Em {
            unsafe { core::mem::transmute(val & 0x03) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Em {
        #[inline(always)]
        fn from(val: u8) -> Em {
            Em::from_bits(val)
        }
    }
    impl From<Em> for u8 {
        #[inline(always)]
        fn from(val: Em) -> u8 {
            Em::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum EvtCfg {
        ///The interrupt or event line is disabled.
        Disable = 0x0,
        ///The interrupt or event line is in software mode. Software must clear the RIS.
        Software = 0x01,
        ///The interrupt or event line is in hardware mode. The hardware (another module) clears automatically the associated RIS flag.
        Hardware = 0x02,
        _RESERVED_3 = 0x03,
    }
    impl EvtCfg {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> EvtCfg {
            unsafe { core::mem::transmute(val & 0x03) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for EvtCfg {
        #[inline(always)]
        fn from(val: u8) -> EvtCfg {
            EvtCfg::from_bits(val)
        }
    }
    impl From<EvtCfg> for u8 {
        #[inline(always)]
        fn from(val: EvtCfg) -> u8 {
            EvtCfg::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum Incr {
        ///Address is unchanged (+0).
        Unchanged = 0x0,
        _RESERVED_1 = 0x01,
        ///Decremented by 1 (-1 * DMADSTWDTH).
        Decrement = 0x02,
        ///Incremented by 1 (+1 * DMADSTWDTH).
        Increment = 0x03,
        _RESERVED_4 = 0x04,
        _RESERVED_5 = 0x05,
        _RESERVED_6 = 0x06,
        _RESERVED_7 = 0x07,
        ///Stride size 2 (+2 * DMADSTWDTH).
        Stride2 = 0x08,
        ///Stride size 3 (+3 * DMADSTWDTH).
        Stride3 = 0x09,
        ///Stride size 4 (+4 * DMADSTWDTH).
        Stride4 = 0x0a,
        ///Stride size 5 (+5 * DMADSTWDTH).
        Stride5 = 0x0b,
        ///Stride size 6 (+6 * DMADSTWDTH).
        Stride6 = 0x0c,
        ///Stride size 7 (+7 * DMADSTWDTH).
        Stride7 = 0x0d,
        ///Stride size 8 (+8 * DMADSTWDTH).
        Stride8 = 0x0e,
        ///Stride size 9 (+9 * DMADSTWDTH).
        Stride9 = 0x0f,
    }
    impl Incr {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Incr {
            unsafe { core::mem::transmute(val & 0x0f) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Incr {
        #[inline(always)]
        fn from(val: u8) -> Incr {
            Incr::from_bits(val)
        }
    }
    impl From<Incr> for u8 {
        #[inline(always)]
        fn from(val: Incr) -> u8 {
            Incr::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum Preirq {
        ///Pre-IRQ event disabled.
        PreirqDisable = 0x0,
        ///Issure Pre-IRQ event when DMASZ=1.
        Preirq1 = 0x01,
        ///Issure Pre-IRQ event when DMASZ=2.
        Preirq2 = 0x02,
        ///Issure Pre-IRQ event when DMASZ=4.
        Preirq4 = 0x03,
        ///Issure Pre-IRQ event when DMASZ=8.
        Preirq8 = 0x04,
        ///Issure Pre-IRQ event when DMASZ=32.
        Preirq32 = 0x05,
        ///Issure Pre-IRQ event when DMASZ=64.
        Preirq64 = 0x06,
        ///Issure Pre-IRQ event when DMASZ reached the half size point of the original transfer size.
        PreirqHalf = 0x07,
    }
    impl Preirq {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Preirq {
            unsafe { core::mem::transmute(val & 0x07) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Preirq {
        #[inline(always)]
        fn from(val: u8) -> Preirq {
            Preirq::from_bits(val)
        }
    }
    impl From<Preirq> for u8 {
        #[inline(always)]
        fn from(val: Preirq) -> u8 {
            Preirq::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum Soft {
        ///The peripheral will halt immediately, even if the resultant state will result in corruption if the system is restarted.
        Immediate = 0x0,
        ///The peripheral blocks the debug freeze until it has reached a boundary where it can resume without corruption.
        Delayed = 0x01,
    }
    impl Soft {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Soft {
            unsafe { core::mem::transmute(val & 0x01) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Soft {
        #[inline(always)]
        fn from(val: u8) -> Soft {
            Soft::from_bits(val)
        }
    }
    impl From<Soft> for u8 {
        #[inline(always)]
        fn from(val: Soft) -> u8 {
            Soft::to_bits(val)
        }
    }
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
    pub struct Stat(u8);
    impl Stat {
        ///No bit is set means there is no pending interrupt request.
        pub const NoIntr: Self = Self(0x0);
        ///DMA Channel 0 size counter reached zero (DMASZ=0).
        pub const Ch0: Self = Self(0x01);
        ///DMA Channel 2 size counter reached zero (DMASZ=0).
        pub const Ch1: Self = Self(0x02);
        ///DMA Channel 2 size counter reached zero (DMASZ=0).
        pub const Ch2: Self = Self(0x03);
        ///DMA Channel 3 size counter reached zero (DMASZ=0).
        pub const Ch3: Self = Self(0x04);
        ///DMA Channel 4 size counter reached zero (DMASZ=0).
        pub const Ch4: Self = Self(0x05);
        ///DMA Channel 5 size counter reached zero (DMASZ=0).
        pub const Ch5: Self = Self(0x06);
        ///DMA Channel 6 size counter reached zero (DMASZ=0).
        pub const Ch6: Self = Self(0x07);
        ///DMA Channel 7 size counter reached zero (DMASZ=0).
        pub const Ch7: Self = Self(0x08);
        ///DMA Channel 8 size counter reached zero (DMASZ=0).
        pub const Ch8: Self = Self(0x09);
        ///DMA Channel 9 size counter reached zero (DMASZ=0).
        pub const Ch9: Self = Self(0x0a);
        ///DMA Channel 10 size counter reached zero (DMASZ=0).
        pub const Ch10: Self = Self(0x0b);
        ///DMA Channel 11 size counter reached zero (DMASZ=0).
        pub const Ch11: Self = Self(0x0c);
        ///DMA Channel 12 size counter reached zero (DMASZ=0).
        pub const Ch12: Self = Self(0x0d);
        ///DMA Channel 13 size counter reached zero (DMASZ=0).
        pub const Ch13: Self = Self(0x0e);
        ///DMA Channel 14 size counter reached zero (DMASZ=0).
        pub const Ch14: Self = Self(0x0f);
        ///DMA Channel 15 size counter reached zero (DMASZ=0).
        pub const Ch15: Self = Self(0x10);
        ///PRE-IRQ event for DMA Channel 0.
        pub const Preirqch0: Self = Self(0x11);
        ///PRE-IRQ event for DMA Channel 1.
        pub const Preirqch1: Self = Self(0x12);
        ///PRE-IRQ event for DMA Channel 2.
        pub const Preirqch2: Self = Self(0x13);
        ///PRE-IRQ event for DMA Channel 3.
        pub const Preirqch3: Self = Self(0x14);
        ///PRE-IRQ event for DMA Channel 4.
        pub const Preirqch4: Self = Self(0x15);
        ///PRE-IRQ event for DMA Channel 5.
        pub const Preirqch5: Self = Self(0x16);
        ///PRE-IRQ event for DMA Channel 6.
        pub const Preirqch6: Self = Self(0x17);
        ///PRE-IRQ event for DMA Channel 7.
        pub const Preirqch7: Self = Self(0x18);
        ///DMA address error, SRC address not reachable.
        pub const Addrerr: Self = Self(0x19);
        ///DMA data error, SRC data might be corrupted (PAR or ECC error).
        pub const Dataerr: Self = Self(0x1a);
    }
    impl Stat {
        pub const fn from_bits(val: u8) -> Stat {
            Self(val & 0xff)
        }
        pub const fn to_bits(self) -> u8 {
            self.0
        }
    }
    impl core::fmt::Debug for Stat {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            match self.0 {
                0x0 => f.write_str("NoIntr"),
                0x01 => f.write_str("Ch0"),
                0x02 => f.write_str("Ch1"),
                0x03 => f.write_str("Ch2"),
                0x04 => f.write_str("Ch3"),
                0x05 => f.write_str("Ch4"),
                0x06 => f.write_str("Ch5"),
                0x07 => f.write_str("Ch6"),
                0x08 => f.write_str("Ch7"),
                0x09 => f.write_str("Ch8"),
                0x0a => f.write_str("Ch9"),
                0x0b => f.write_str("Ch10"),
                0x0c => f.write_str("Ch11"),
                0x0d => f.write_str("Ch12"),
                0x0e => f.write_str("Ch13"),
                0x0f => f.write_str("Ch14"),
                0x10 => f.write_str("Ch15"),
                0x11 => f.write_str("Preirqch0"),
                0x12 => f.write_str("Preirqch1"),
                0x13 => f.write_str("Preirqch2"),
                0x14 => f.write_str("Preirqch3"),
                0x15 => f.write_str("Preirqch4"),
                0x16 => f.write_str("Preirqch5"),
                0x17 => f.write_str("Preirqch6"),
                0x18 => f.write_str("Preirqch7"),
                0x19 => f.write_str("Addrerr"),
                0x1a => f.write_str("Dataerr"),
                other => core::write!(f, "0x{:02X}", other),
            }
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Stat {
        fn format(&self, f: defmt::Formatter) {
            match self.0 {
                0x0 => defmt::write!(f, "NoIntr"),
                0x01 => defmt::write!(f, "Ch0"),
                0x02 => defmt::write!(f, "Ch1"),
                0x03 => defmt::write!(f, "Ch2"),
                0x04 => defmt::write!(f, "Ch3"),
                0x05 => defmt::write!(f, "Ch4"),
                0x06 => defmt::write!(f, "Ch5"),
                0x07 => defmt::write!(f, "Ch6"),
                0x08 => defmt::write!(f, "Ch7"),
                0x09 => defmt::write!(f, "Ch8"),
                0x0a => defmt::write!(f, "Ch9"),
                0x0b => defmt::write!(f, "Ch10"),
                0x0c => defmt::write!(f, "Ch11"),
                0x0d => defmt::write!(f, "Ch12"),
                0x0e => defmt::write!(f, "Ch13"),
                0x0f => defmt::write!(f, "Ch14"),
                0x10 => defmt::write!(f, "Ch15"),
                0x11 => defmt::write!(f, "Preirqch0"),
                0x12 => defmt::write!(f, "Preirqch1"),
                0x13 => defmt::write!(f, "Preirqch2"),
                0x14 => defmt::write!(f, "Preirqch3"),
                0x15 => defmt::write!(f, "Preirqch4"),
                0x16 => defmt::write!(f, "Preirqch5"),
                0x17 => defmt::write!(f, "Preirqch6"),
                0x18 => defmt::write!(f, "Preirqch7"),
                0x19 => defmt::write!(f, "Addrerr"),
                0x1a => defmt::write!(f, "Dataerr"),
                other => defmt::write!(f, "0x{:02X}", other),
            }
        }
    }
    impl From<u8> for Stat {
        #[inline(always)]
        fn from(val: u8) -> Stat {
            Stat::from_bits(val)
        }
    }
    impl From<Stat> for u8 {
        #[inline(always)]
        fn from(val: Stat) -> u8 {
            Stat::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum Tint {
        ///DMATSEL will define external trigger select as transfer trigger.
        External = 0x0,
        ///DMATSEL will define internal channel as transfer trigger select. 0-> Channel0-done, 1-> Channel1-done, ...
        Internal = 0x01,
    }
    impl Tint {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Tint {
            unsafe { core::mem::transmute(val & 0x01) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Tint {
        #[inline(always)]
        fn from(val: u8) -> Tint {
            Tint::from_bits(val)
        }
    }
    impl From<Tint> for u8 {
        #[inline(always)]
        fn from(val: Tint) -> u8 {
            Tint::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum Tm {
        ///Single transfer. Each transfers requires a new trigger. When the DMASZ counts down to zero an event can be generated and the DMAEN is cleared.
        Single = 0x0,
        ///Block transfer. Each trigger transfers the complete block defined in DMASZ. After the transfer is complete an event can be generated and the DMAEN is cleared.
        Block = 0x01,
        ///Repeated single transfer. Each transfers requires a new trigger. When the DMASZ counts down to zero an event can be generated. After the last transfer the DMASA, DMADA, DAMSZ registers are restored to its initial value and the DMAEN stays enabled.
        Rptsngl = 0x02,
        ///Repeated block transfer. Each trigger transfers the complete block defined in DMASZ. After the last transfer the DMASA, DMADA, DAMSZ registers are restored to its initial value and the DMAEN stays enabled.
        Rptblck = 0x03,
    }
    impl Tm {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Tm {
            unsafe { core::mem::transmute(val & 0x03) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Tm {
        #[inline(always)]
        fn from(val: u8) -> Tm {
            Tm::from_bits(val)
        }
    }
    impl From<Tm> for u8 {
        #[inline(always)]
        fn from(val: Tm) -> u8 {
            Tm::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum Wdth {
        ///Destination data width is BYTE (8-bit).
        Byte = 0x0,
        ///Destination data width is HALF-WORD (16-bit).
        Half = 0x01,
        ///Destination data width is WORD (32-bit).
        Word = 0x02,
        ///Destination data width is LONG-WORD (64-bit).
        Long = 0x03,
    }
    impl Wdth {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Wdth {
            unsafe { core::mem::transmute(val & 0x03) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Wdth {
        #[inline(always)]
        fn from(val: u8) -> Wdth {
            Wdth::from_bits(val)
        }
    }
    impl From<Wdth> for u8 {
        #[inline(always)]
        fn from(val: Wdth) -> u8 {
            Wdth::to_bits(val)
        }
    }
}
