// This file is autogenerated by mspm0-metapac-gen: do not edit by hand.
#![allow(clippy::missing_safety_doc)]
#![allow(clippy::identity_op)]
#![allow(clippy::unnecessary_cast)]
#![allow(clippy::erasing_op)]
///Customer-visible factory constants (IDs, PLL trims, calibration).
#[derive(Copy, Clone, Eq, PartialEq)]
pub struct Factoryregion {
    ptr: *mut u8,
}
unsafe impl Send for Factoryregion {}
unsafe impl Sync for Factoryregion {}
impl Factoryregion {
    #[inline(always)]
    pub const unsafe fn from_ptr(ptr: *mut ()) -> Self {
        Self { ptr: ptr as _ }
    }
    #[inline(always)]
    pub const fn as_ptr(&self) -> *mut () {
        self.ptr as _
    }
    ///Defined by TI, during ATE, based on wafer.
    #[inline(always)]
    pub const fn traceid(self) -> crate::common::Reg<u32, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x0usize) as _) }
    }
    ///This is the JTAGIDCODE that comes from the Ramp system.
    #[inline(always)]
    pub const fn deviceid(self) -> crate::common::Reg<regs::Deviceid, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x04usize) as _) }
    }
    ///Defined by TI, depending on device spin.
    #[inline(always)]
    pub const fn userid(self) -> crate::common::Reg<regs::Userid, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x08usize) as _) }
    }
    ///BSL UART Pin Configuration.
    #[inline(always)]
    pub const fn bslpin_uart(
        self,
    ) -> crate::common::Reg<regs::BslpinUart, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x0cusize) as _) }
    }
    ///BSL I2C Pin Configuration.
    #[inline(always)]
    pub const fn bslpin_i2c(
        self,
    ) -> crate::common::Reg<regs::BslpinI2c, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x10usize) as _) }
    }
    ///BSL Pin Invocation Configuration.
    #[inline(always)]
    pub const fn bslpin_invoke(
        self,
    ) -> crate::common::Reg<regs::BslpinInvoke, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x14usize) as _) }
    }
    ///SRAM and flash sizes.
    #[inline(always)]
    pub const fn sramflash(
        self,
    ) -> crate::common::Reg<regs::Sramflash, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x18usize) as _) }
    }
    ///System PLL Parameter 0 MMR for a 4 to 8 MHz reference clock.
    #[inline(always)]
    pub const fn pllstartup0_4_8mhz(
        self,
    ) -> crate::common::Reg<regs::Pllstartup0, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x1cusize) as _) }
    }
    ///System PLL Parameter 1 MMR for a 4 to 8 MHz reference clock.
    #[inline(always)]
    pub const fn pllstartup1_4_8mhz(
        self,
    ) -> crate::common::Reg<regs::Pllstartup1, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x20usize) as _) }
    }
    ///System PLL Parameter 0 MMR for a 8 to 16 MHz reference clock.
    #[inline(always)]
    pub const fn pllstartup0_8_16mhz(
        self,
    ) -> crate::common::Reg<regs::Pllstartup0, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x24usize) as _) }
    }
    ///System PLL Parameter 1 MMR for a 8 to 16 MHz reference clock.
    #[inline(always)]
    pub const fn pllstartup1_8_16mhz(
        self,
    ) -> crate::common::Reg<regs::Pllstartup1, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x28usize) as _) }
    }
    ///System PLL Parameter 0 MMR for a 16 to 32 MHz reference clock.
    #[inline(always)]
    pub const fn pllstartup0_16_32mhz(
        self,
    ) -> crate::common::Reg<regs::Pllstartup0, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x2cusize) as _) }
    }
    ///System PLL Parameter 1 MMR for a 16 to 32 MHz reference clock.
    #[inline(always)]
    pub const fn pllstartup1_16_32mhz(
        self,
    ) -> crate::common::Reg<regs::Pllstartup1, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x30usize) as _) }
    }
    ///System PLL Parameter 0 MMR for a 32 to 48 MHz reference clock.
    #[inline(always)]
    pub const fn pllstartup0_32_48mhz(
        self,
    ) -> crate::common::Reg<regs::Pllstartup0, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x34usize) as _) }
    }
    ///System PLL Parameter 1 MMR for a 32 to 48 MHz reference clock.
    #[inline(always)]
    pub const fn pllstartup1_32_48mhz(
        self,
    ) -> crate::common::Reg<regs::Pllstartup1, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x38usize) as _) }
    }
    ///Temperature sensor room temperature calibration code. This is the ADC conversion result of the temperature sensor output voltage. Included in BOOTCRC calculation.
    #[inline(always)]
    pub const fn temp_sense0(self) -> crate::common::Reg<u32, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x3cusize) as _) }
    }
    ///BOOTCRC records the 32-bit CRC of all locations in OPEN including reserved locations.
    #[inline(always)]
    pub const fn bootcrc(self) -> crate::common::Reg<u32, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x7cusize) as _) }
    }
}
pub mod regs {
    ///BSL I2C Pin Configuration.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct BslpinI2c(pub u32);
    impl BslpinI2c {
        ///I2C SDA Pin used by BSL.
        #[must_use]
        #[inline(always)]
        pub const fn i2c_sda_pad(&self) -> u8 {
            let val = (self.0 >> 0usize) & 0xff;
            val as u8
        }
        ///I2C SDA Pin used by BSL.
        #[inline(always)]
        pub const fn set_i2c_sda_pad(&mut self, val: u8) {
            self.0 = (self.0 & !(0xff << 0usize)) | (((val as u32) & 0xff) << 0usize);
        }
        ///I2C SDA Pin Function Selection Value.
        #[must_use]
        #[inline(always)]
        pub const fn i2c_sda_pf(&self) -> u8 {
            let val = (self.0 >> 8usize) & 0xff;
            val as u8
        }
        ///I2C SDA Pin Function Selection Value.
        #[inline(always)]
        pub const fn set_i2c_sda_pf(&mut self, val: u8) {
            self.0 = (self.0 & !(0xff << 8usize)) | (((val as u32) & 0xff) << 8usize);
        }
        ///I2C SCL Pin used by BSL.
        #[must_use]
        #[inline(always)]
        pub const fn i2c_scl_pad(&self) -> u8 {
            let val = (self.0 >> 16usize) & 0xff;
            val as u8
        }
        ///I2C SCL Pin used by BSL.
        #[inline(always)]
        pub const fn set_i2c_scl_pad(&mut self, val: u8) {
            self.0 = (self.0 & !(0xff << 16usize)) | (((val as u32) & 0xff) << 16usize);
        }
        ///I2C SCL Pin Function Selection Value.
        #[must_use]
        #[inline(always)]
        pub const fn i2c_scl_pf(&self) -> u8 {
            let val = (self.0 >> 24usize) & 0xff;
            val as u8
        }
        ///I2C SCL Pin Function Selection Value.
        #[inline(always)]
        pub const fn set_i2c_scl_pf(&mut self, val: u8) {
            self.0 = (self.0 & !(0xff << 24usize)) | (((val as u32) & 0xff) << 24usize);
        }
    }
    impl Default for BslpinI2c {
        #[inline(always)]
        fn default() -> BslpinI2c {
            BslpinI2c(0)
        }
    }
    impl core::fmt::Debug for BslpinI2c {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("BslpinI2c")
                .field("i2c_sda_pad", &self.i2c_sda_pad())
                .field("i2c_sda_pf", &self.i2c_sda_pf())
                .field("i2c_scl_pad", &self.i2c_scl_pad())
                .field("i2c_scl_pf", &self.i2c_scl_pf())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for BslpinI2c {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f,
                "BslpinI2c {{ i2c_sda_pad: {=u8:?}, i2c_sda_pf: {=u8:?}, i2c_scl_pad: {=u8:?}, i2c_scl_pf: {=u8:?} }}",
                self.i2c_sda_pad(), self.i2c_sda_pf(), self.i2c_scl_pad(), self
                .i2c_scl_pf()
            )
        }
    }
    ///BSL Pin Invocation Configuration.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct BslpinInvoke(pub u32);
    impl BslpinInvoke {
        ///BSL Invocation Pin Number.
        #[must_use]
        #[inline(always)]
        pub const fn bsl_pad(&self) -> u8 {
            let val = (self.0 >> 0usize) & 0x7f;
            val as u8
        }
        ///BSL Invocation Pin Number.
        #[inline(always)]
        pub const fn set_bsl_pad(&mut self, val: u8) {
            self.0 = (self.0 & !(0x7f << 0usize)) | (((val as u32) & 0x7f) << 0usize);
        }
        ///GPIO Level Configuration for BSL Invocation.
        #[must_use]
        #[inline(always)]
        pub const fn gpio_level(&self) -> bool {
            let val = (self.0 >> 7usize) & 0x01;
            val != 0
        }
        ///GPIO Level Configuration for BSL Invocation.
        #[inline(always)]
        pub const fn set_gpio_level(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize);
        }
        ///GPIO Pin Number in GPIO Module.
        #[must_use]
        #[inline(always)]
        pub const fn gpio_pin_sel(&self) -> u8 {
            let val = (self.0 >> 8usize) & 0x1f;
            val as u8
        }
        ///GPIO Pin Number in GPIO Module.
        #[inline(always)]
        pub const fn set_gpio_pin_sel(&mut self, val: u8) {
            self.0 = (self.0 & !(0x1f << 8usize)) | (((val as u32) & 0x1f) << 8usize);
        }
        ///GPIO Module Selection.
        #[must_use]
        #[inline(always)]
        pub const fn gpio_reg_sel(&self) -> u8 {
            let val = (self.0 >> 13usize) & 0x03;
            val as u8
        }
        ///GPIO Module Selection.
        #[inline(always)]
        pub const fn set_gpio_reg_sel(&mut self, val: u8) {
            self.0 = (self.0 & !(0x03 << 13usize)) | (((val as u32) & 0x03) << 13usize);
        }
    }
    impl Default for BslpinInvoke {
        #[inline(always)]
        fn default() -> BslpinInvoke {
            BslpinInvoke(0)
        }
    }
    impl core::fmt::Debug for BslpinInvoke {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("BslpinInvoke")
                .field("bsl_pad", &self.bsl_pad())
                .field("gpio_level", &self.gpio_level())
                .field("gpio_pin_sel", &self.gpio_pin_sel())
                .field("gpio_reg_sel", &self.gpio_reg_sel())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for BslpinInvoke {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f,
                "BslpinInvoke {{ bsl_pad: {=u8:?}, gpio_level: {=bool:?}, gpio_pin_sel: {=u8:?}, gpio_reg_sel: {=u8:?} }}",
                self.bsl_pad(), self.gpio_level(), self.gpio_pin_sel(), self
                .gpio_reg_sel()
            )
        }
    }
    ///BSL UART Pin Configuration.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct BslpinUart(pub u32);
    impl BslpinUart {
        ///UART RXD Pad used by BSL.
        #[must_use]
        #[inline(always)]
        pub const fn uart_rxd_pad(&self) -> u8 {
            let val = (self.0 >> 0usize) & 0xff;
            val as u8
        }
        ///UART RXD Pad used by BSL.
        #[inline(always)]
        pub const fn set_uart_rxd_pad(&mut self, val: u8) {
            self.0 = (self.0 & !(0xff << 0usize)) | (((val as u32) & 0xff) << 0usize);
        }
        ///UART RXD Pin Function Selection Value.
        #[must_use]
        #[inline(always)]
        pub const fn uart_rxd_pf(&self) -> u8 {
            let val = (self.0 >> 8usize) & 0xff;
            val as u8
        }
        ///UART RXD Pin Function Selection Value.
        #[inline(always)]
        pub const fn set_uart_rxd_pf(&mut self, val: u8) {
            self.0 = (self.0 & !(0xff << 8usize)) | (((val as u32) & 0xff) << 8usize);
        }
        ///UART TXD Pin used by BSL.
        #[must_use]
        #[inline(always)]
        pub const fn uart_txd_pad(&self) -> u8 {
            let val = (self.0 >> 16usize) & 0xff;
            val as u8
        }
        ///UART TXD Pin used by BSL.
        #[inline(always)]
        pub const fn set_uart_txd_pad(&mut self, val: u8) {
            self.0 = (self.0 & !(0xff << 16usize)) | (((val as u32) & 0xff) << 16usize);
        }
        ///UART TXD Pin Function Selection Value.
        #[must_use]
        #[inline(always)]
        pub const fn uart_txd_pf(&self) -> u8 {
            let val = (self.0 >> 24usize) & 0xff;
            val as u8
        }
        ///UART TXD Pin Function Selection Value.
        #[inline(always)]
        pub const fn set_uart_txd_pf(&mut self, val: u8) {
            self.0 = (self.0 & !(0xff << 24usize)) | (((val as u32) & 0xff) << 24usize);
        }
    }
    impl Default for BslpinUart {
        #[inline(always)]
        fn default() -> BslpinUart {
            BslpinUart(0)
        }
    }
    impl core::fmt::Debug for BslpinUart {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("BslpinUart")
                .field("uart_rxd_pad", &self.uart_rxd_pad())
                .field("uart_rxd_pf", &self.uart_rxd_pf())
                .field("uart_txd_pad", &self.uart_txd_pad())
                .field("uart_txd_pf", &self.uart_txd_pf())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for BslpinUart {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f,
                "BslpinUart {{ uart_rxd_pad: {=u8:?}, uart_rxd_pf: {=u8:?}, uart_txd_pad: {=u8:?}, uart_txd_pf: {=u8:?} }}",
                self.uart_rxd_pad(), self.uart_rxd_pf(), self.uart_txd_pad(), self
                .uart_txd_pf()
            )
        }
    }
    ///This is the JTAGIDCODE that comes from the Ramp system.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Deviceid(pub u32);
    impl Deviceid {
        ///TI's JEDEC bank and company code.
        #[must_use]
        #[inline(always)]
        pub const fn manufacturer(&self) -> u16 {
            let val = (self.0 >> 1usize) & 0x07ff;
            val as u16
        }
        ///TI's JEDEC bank and company code.
        #[inline(always)]
        pub const fn set_manufacturer(&mut self, val: u16) {
            self.0 = (self.0 & !(0x07ff << 1usize))
                | (((val as u32) & 0x07ff) << 1usize);
        }
        ///Part number of the device.
        #[must_use]
        #[inline(always)]
        pub const fn partnum(&self) -> u16 {
            let val = (self.0 >> 12usize) & 0xffff;
            val as u16
        }
        ///Part number of the device.
        #[inline(always)]
        pub const fn set_partnum(&mut self, val: u16) {
            self.0 = (self.0 & !(0xffff << 12usize))
                | (((val as u32) & 0xffff) << 12usize);
        }
        ///Revision of the device.
        #[must_use]
        #[inline(always)]
        pub const fn version(&self) -> u8 {
            let val = (self.0 >> 28usize) & 0x0f;
            val as u8
        }
        ///Revision of the device.
        #[inline(always)]
        pub const fn set_version(&mut self, val: u8) {
            self.0 = (self.0 & !(0x0f << 28usize)) | (((val as u32) & 0x0f) << 28usize);
        }
    }
    impl Default for Deviceid {
        #[inline(always)]
        fn default() -> Deviceid {
            Deviceid(0)
        }
    }
    impl core::fmt::Debug for Deviceid {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Deviceid")
                .field("manufacturer", &self.manufacturer())
                .field("partnum", &self.partnum())
                .field("version", &self.version())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Deviceid {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f,
                "Deviceid {{ manufacturer: {=u16:?}, partnum: {=u16:?}, version: {=u8:?} }}",
                self.manufacturer(), self.partnum(), self.version()
            )
        }
    }
    ///System PLL Parameter 0 MMR.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Pllstartup0(pub u32);
    impl Pllstartup0 {
        ///Startup time from Enable to Locked Clock in resolution of 1usec.
        #[must_use]
        #[inline(always)]
        pub const fn starttime(&self) -> u8 {
            let val = (self.0 >> 0usize) & 0x3f;
            val as u8
        }
        ///Startup time from Enable to Locked Clock in resolution of 1usec.
        #[inline(always)]
        pub const fn set_starttime(&mut self, val: u8) {
            self.0 = (self.0 & !(0x3f << 0usize)) | (((val as u32) & 0x3f) << 0usize);
        }
        ///Startup time from Low Power Exit to Locked Clock in resolution of 1usec.
        #[must_use]
        #[inline(always)]
        pub const fn starttimelp(&self) -> u8 {
            let val = (self.0 >> 8usize) & 0x3f;
            val as u8
        }
        ///Startup time from Low Power Exit to Locked Clock in resolution of 1usec.
        #[inline(always)]
        pub const fn set_starttimelp(&mut self, val: u8) {
            self.0 = (self.0 & !(0x3f << 8usize)) | (((val as u32) & 0x3f) << 8usize);
        }
        ///Charge Pump Current.
        #[must_use]
        #[inline(always)]
        pub const fn cpcurrent(&self) -> u8 {
            let val = (self.0 >> 16usize) & 0x3f;
            val as u8
        }
        ///Charge Pump Current.
        #[inline(always)]
        pub const fn set_cpcurrent(&mut self, val: u8) {
            self.0 = (self.0 & !(0x3f << 16usize)) | (((val as u32) & 0x3f) << 16usize);
        }
        ///Override Value for Cap B.
        #[must_use]
        #[inline(always)]
        pub const fn capbval(&self) -> u8 {
            let val = (self.0 >> 24usize) & 0x1f;
            val as u8
        }
        ///Override Value for Cap B.
        #[inline(always)]
        pub const fn set_capbval(&mut self, val: u8) {
            self.0 = (self.0 & !(0x1f << 24usize)) | (((val as u32) & 0x1f) << 24usize);
        }
        ///Override Enable For Cap B.
        #[must_use]
        #[inline(always)]
        pub const fn capboverride(&self) -> bool {
            let val = (self.0 >> 31usize) & 0x01;
            val != 0
        }
        ///Override Enable For Cap B.
        #[inline(always)]
        pub const fn set_capboverride(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize);
        }
    }
    impl Default for Pllstartup0 {
        #[inline(always)]
        fn default() -> Pllstartup0 {
            Pllstartup0(0)
        }
    }
    impl core::fmt::Debug for Pllstartup0 {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Pllstartup0")
                .field("starttime", &self.starttime())
                .field("starttimelp", &self.starttimelp())
                .field("cpcurrent", &self.cpcurrent())
                .field("capbval", &self.capbval())
                .field("capboverride", &self.capboverride())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Pllstartup0 {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f,
                "Pllstartup0 {{ starttime: {=u8:?}, starttimelp: {=u8:?}, cpcurrent: {=u8:?}, capbval: {=u8:?}, capboverride: {=bool:?} }}",
                self.starttime(), self.starttimelp(), self.cpcurrent(), self.capbval(),
                self.capboverride()
            )
        }
    }
    ///System PLL Parameter 1 MMR.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Pllstartup1(pub u32);
    impl Pllstartup1 {
        ///Loop Filter Cap A.
        #[must_use]
        #[inline(always)]
        pub const fn lpfcapa(&self) -> u8 {
            let val = (self.0 >> 0usize) & 0x1f;
            val as u8
        }
        ///Loop Filter Cap A.
        #[inline(always)]
        pub const fn set_lpfcapa(&mut self, val: u8) {
            self.0 = (self.0 & !(0x1f << 0usize)) | (((val as u32) & 0x1f) << 0usize);
        }
        ///Loop Filter Res A.
        #[must_use]
        #[inline(always)]
        pub const fn lpfresa(&self) -> u16 {
            let val = (self.0 >> 8usize) & 0x03ff;
            val as u16
        }
        ///Loop Filter Res A.
        #[inline(always)]
        pub const fn set_lpfresa(&mut self, val: u16) {
            self.0 = (self.0 & !(0x03ff << 8usize))
                | (((val as u32) & 0x03ff) << 8usize);
        }
        ///Loop Filter Res C.
        #[must_use]
        #[inline(always)]
        pub const fn lpfresc(&self) -> u8 {
            let val = (self.0 >> 24usize) & 0xff;
            val as u8
        }
        ///Loop Filter Res C.
        #[inline(always)]
        pub const fn set_lpfresc(&mut self, val: u8) {
            self.0 = (self.0 & !(0xff << 24usize)) | (((val as u32) & 0xff) << 24usize);
        }
    }
    impl Default for Pllstartup1 {
        #[inline(always)]
        fn default() -> Pllstartup1 {
            Pllstartup1(0)
        }
    }
    impl core::fmt::Debug for Pllstartup1 {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Pllstartup1")
                .field("lpfcapa", &self.lpfcapa())
                .field("lpfresa", &self.lpfresa())
                .field("lpfresc", &self.lpfresc())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Pllstartup1 {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f,
                "Pllstartup1 {{ lpfcapa: {=u8:?}, lpfresa: {=u16:?}, lpfresc: {=u8:?} }}",
                self.lpfcapa(), self.lpfresa(), self.lpfresc()
            )
        }
    }
    ///SRAM and flash sizes.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Sramflash(pub u32);
    impl Sramflash {
        ///Size of main flash in KB.
        #[must_use]
        #[inline(always)]
        pub const fn mainflash_sz(&self) -> u16 {
            let val = (self.0 >> 0usize) & 0x0fff;
            val as u16
        }
        ///Size of main flash in KB.
        #[inline(always)]
        pub const fn set_mainflash_sz(&mut self, val: u16) {
            self.0 = (self.0 & !(0x0fff << 0usize))
                | (((val as u32) & 0x0fff) << 0usize);
        }
        ///Number of banks in main flash.
        #[must_use]
        #[inline(always)]
        pub const fn mainnumbanks(&self) -> super::vals::Mainnumbanks {
            let val = (self.0 >> 12usize) & 0x03;
            super::vals::Mainnumbanks::from_bits(val as u8)
        }
        ///Number of banks in main flash.
        #[inline(always)]
        pub const fn set_mainnumbanks(&mut self, val: super::vals::Mainnumbanks) {
            self.0 = (self.0 & !(0x03 << 12usize))
                | (((val.to_bits() as u32) & 0x03) << 12usize);
        }
        ///Size of SRAM in KB.
        #[must_use]
        #[inline(always)]
        pub const fn sram_sz(&self) -> u16 {
            let val = (self.0 >> 16usize) & 0x03ff;
            val as u16
        }
        ///Size of SRAM in KB.
        #[inline(always)]
        pub const fn set_sram_sz(&mut self, val: u16) {
            self.0 = (self.0 & !(0x03ff << 16usize))
                | (((val as u32) & 0x03ff) << 16usize);
        }
        ///Size of data flash in KB.
        #[must_use]
        #[inline(always)]
        pub const fn dataflash_sz(&self) -> u8 {
            let val = (self.0 >> 26usize) & 0x3f;
            val as u8
        }
        ///Size of data flash in KB.
        #[inline(always)]
        pub const fn set_dataflash_sz(&mut self, val: u8) {
            self.0 = (self.0 & !(0x3f << 26usize)) | (((val as u32) & 0x3f) << 26usize);
        }
    }
    impl Default for Sramflash {
        #[inline(always)]
        fn default() -> Sramflash {
            Sramflash(0)
        }
    }
    impl core::fmt::Debug for Sramflash {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Sramflash")
                .field("mainflash_sz", &self.mainflash_sz())
                .field("mainnumbanks", &self.mainnumbanks())
                .field("sram_sz", &self.sram_sz())
                .field("dataflash_sz", &self.dataflash_sz())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Sramflash {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f,
                "Sramflash {{ mainflash_sz: {=u16:?}, mainnumbanks: {:?}, sram_sz: {=u16:?}, dataflash_sz: {=u8:?} }}",
                self.mainflash_sz(), self.mainnumbanks(), self.sram_sz(), self
                .dataflash_sz()
            )
        }
    }
    ///Defined by TI, depending on device spin.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Userid(pub u32);
    impl Userid {
        ///Bit pattern that uniquely identifies the part number of the device.
        #[must_use]
        #[inline(always)]
        pub const fn part(&self) -> u16 {
            let val = (self.0 >> 0usize) & 0xffff;
            val as u16
        }
        ///Bit pattern that uniquely identifies the part number of the device.
        #[inline(always)]
        pub const fn set_part(&mut self, val: u16) {
            self.0 = (self.0 & !(0xffff << 0usize))
                | (((val as u32) & 0xffff) << 0usize);
        }
        ///Bit pattern uniquely identifying a variant of the part number.
        #[must_use]
        #[inline(always)]
        pub const fn variant(&self) -> u8 {
            let val = (self.0 >> 16usize) & 0xff;
            val as u8
        }
        ///Bit pattern uniquely identifying a variant of the part number.
        #[inline(always)]
        pub const fn set_variant(&mut self, val: u8) {
            self.0 = (self.0 & !(0xff << 16usize)) | (((val as u32) & 0xff) << 16usize);
        }
        ///Monotonic increasing value indicating the minor revision of the device.
        #[must_use]
        #[inline(always)]
        pub const fn minorrev(&self) -> u8 {
            let val = (self.0 >> 24usize) & 0x0f;
            val as u8
        }
        ///Monotonic increasing value indicating the minor revision of the device.
        #[inline(always)]
        pub const fn set_minorrev(&mut self, val: u8) {
            self.0 = (self.0 & !(0x0f << 24usize)) | (((val as u32) & 0x0f) << 24usize);
        }
        ///Monotonic increasing value indicating the major revision of the device.
        #[must_use]
        #[inline(always)]
        pub const fn majorrev(&self) -> u8 {
            let val = (self.0 >> 28usize) & 0x07;
            val as u8
        }
        ///Monotonic increasing value indicating the major revision of the device.
        #[inline(always)]
        pub const fn set_majorrev(&mut self, val: u8) {
            self.0 = (self.0 & !(0x07 << 28usize)) | (((val as u32) & 0x07) << 28usize);
        }
        ///Start bit.
        #[must_use]
        #[inline(always)]
        pub const fn start(&self) -> bool {
            let val = (self.0 >> 31usize) & 0x01;
            val != 0
        }
        ///Start bit.
        #[inline(always)]
        pub const fn set_start(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize);
        }
    }
    impl Default for Userid {
        #[inline(always)]
        fn default() -> Userid {
            Userid(0)
        }
    }
    impl core::fmt::Debug for Userid {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Userid")
                .field("part", &self.part())
                .field("variant", &self.variant())
                .field("minorrev", &self.minorrev())
                .field("majorrev", &self.majorrev())
                .field("start", &self.start())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Userid {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f,
                "Userid {{ part: {=u16:?}, variant: {=u8:?}, minorrev: {=u8:?}, majorrev: {=u8:?}, start: {=bool:?} }}",
                self.part(), self.variant(), self.minorrev(), self.majorrev(), self
                .start()
            )
        }
    }
}
pub mod vals {
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum Mainnumbanks {
        ///One bank.
        Onebank = 0x0,
        ///Two banks.
        Twobanks = 0x01,
        ///Three banks.
        Threebanks = 0x02,
        ///Four banks.
        Fourbanks = 0x03,
    }
    impl Mainnumbanks {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Mainnumbanks {
            unsafe { core::mem::transmute(val & 0x03) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Mainnumbanks {
        #[inline(always)]
        fn from(val: u8) -> Mainnumbanks {
            Mainnumbanks::from_bits(val)
        }
    }
    impl From<Mainnumbanks> for u8 {
        #[inline(always)]
        fn from(val: Mainnumbanks) -> u8 {
            Mainnumbanks::to_bits(val)
        }
    }
}
