// This file is autogenerated by mspm0-metapac-gen: do not edit by hand.
#![allow(clippy::missing_safety_doc)]
#![allow(clippy::identity_op)]
#![allow(clippy::unnecessary_cast)]
#![allow(clippy::erasing_op)]
#[derive(Copy, Clone, Eq, PartialEq)]
pub struct CpuInt {
    ptr: *mut u8,
}
unsafe impl Send for CpuInt {}
unsafe impl Sync for CpuInt {}
impl CpuInt {
    #[inline(always)]
    pub const unsafe fn from_ptr(ptr: *mut ()) -> Self {
        Self { ptr: ptr as _ }
    }
    #[inline(always)]
    pub const fn as_ptr(&self) -> *mut () {
        self.ptr as _
    }
    ///Interrupt index.
    #[inline(always)]
    pub const fn iidx(self) -> crate::common::Reg<regs::Iidx, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x0usize) as _) }
    }
    ///Interrupt mask.
    #[inline(always)]
    pub const fn imask(self) -> crate::common::Reg<regs::Int, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x08usize) as _) }
    }
    ///Raw interrupt status.
    #[inline(always)]
    pub const fn ris(self) -> crate::common::Reg<regs::Int, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x10usize) as _) }
    }
    ///Masked interrupt status.
    #[inline(always)]
    pub const fn mis(self) -> crate::common::Reg<regs::Int, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x18usize) as _) }
    }
    ///Interrupt set.
    #[inline(always)]
    pub const fn iset(self) -> crate::common::Reg<regs::Int, crate::common::W> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x20usize) as _) }
    }
    ///Interrupt clear.
    #[inline(always)]
    pub const fn iclr(self) -> crate::common::Reg<regs::Int, crate::common::W> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x28usize) as _) }
    }
}
#[derive(Copy, Clone, Eq, PartialEq)]
pub struct Gprcm {
    ptr: *mut u8,
}
unsafe impl Send for Gprcm {}
unsafe impl Sync for Gprcm {}
impl Gprcm {
    #[inline(always)]
    pub const unsafe fn from_ptr(ptr: *mut ()) -> Self {
        Self { ptr: ptr as _ }
    }
    #[inline(always)]
    pub const fn as_ptr(&self) -> *mut () {
        self.ptr as _
    }
    ///Power enable.
    #[inline(always)]
    pub const fn pwren(self) -> crate::common::Reg<regs::Pwren, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x0usize) as _) }
    }
    ///Reset Control.
    #[inline(always)]
    pub const fn rstctl(self) -> crate::common::Reg<regs::Rstctl, crate::common::W> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x04usize) as _) }
    }
    ///Status Register.
    #[inline(always)]
    pub const fn stat(self) -> crate::common::Reg<regs::Stat, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x14usize) as _) }
    }
}
///WWDT.
#[derive(Copy, Clone, Eq, PartialEq)]
pub struct Wwdt {
    ptr: *mut u8,
}
unsafe impl Send for Wwdt {}
unsafe impl Sync for Wwdt {}
impl Wwdt {
    #[inline(always)]
    pub const unsafe fn from_ptr(ptr: *mut ()) -> Self {
        Self { ptr: ptr as _ }
    }
    #[inline(always)]
    pub const fn as_ptr(&self) -> *mut () {
        self.ptr as _
    }
    #[inline(always)]
    pub const fn gprcm(self, n: usize) -> Gprcm {
        assert!(n < 1usize);
        unsafe { Gprcm::from_ptr(self.ptr.wrapping_add(0x0800usize + n * 24usize) as _) }
    }
    ///Peripheral Debug Control.
    #[inline(always)]
    pub const fn pdbgctl(self) -> crate::common::Reg<regs::Pdbgctl, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x1018usize) as _) }
    }
    #[inline(always)]
    pub const fn cpu_int(self, n: usize) -> CpuInt {
        assert!(n < 1usize);
        unsafe {
            CpuInt::from_ptr(self.ptr.wrapping_add(0x1020usize + n * 44usize) as _)
        }
    }
    ///Event Mode.
    #[inline(always)]
    pub const fn evt_mode(self) -> crate::common::Reg<regs::EvtMode, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x10e0usize) as _) }
    }
    ///Module Description.
    #[inline(always)]
    pub const fn desc(self) -> crate::common::Reg<regs::Desc, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x10fcusize) as _) }
    }
    ///Window Watchdog Timer Control Register 0.
    #[inline(always)]
    pub const fn wwdtctl0(
        self,
    ) -> crate::common::Reg<regs::Wwdtctl0, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x1100usize) as _) }
    }
    ///Window Watchdog Timer Control Register 0.
    #[inline(always)]
    pub const fn wwdtctl1(
        self,
    ) -> crate::common::Reg<regs::Wwdtctl1, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x1104usize) as _) }
    }
    ///Window Watchdog Timer Counter Reset Register.
    #[inline(always)]
    pub const fn wwdtcntrst(
        self,
    ) -> crate::common::Reg<regs::Wwdtcntrst, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x1108usize) as _) }
    }
    ///Window Watchdog Timer Status Register.
    #[inline(always)]
    pub const fn wwdtstat(self) -> crate::common::Reg<regs::Wwdtstat, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x110cusize) as _) }
    }
}
pub mod regs {
    ///Module Description.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Desc(pub u32);
    impl Desc {
        ///Minor rev of the IP.
        #[must_use]
        #[inline(always)]
        pub const fn minrev(&self) -> u8 {
            let val = (self.0 >> 0usize) & 0x0f;
            val as u8
        }
        ///Minor rev of the IP.
        #[inline(always)]
        pub const fn set_minrev(&mut self, val: u8) {
            self.0 = (self.0 & !(0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize);
        }
        ///Major rev of the IP.
        #[must_use]
        #[inline(always)]
        pub const fn majrev(&self) -> u8 {
            let val = (self.0 >> 4usize) & 0x0f;
            val as u8
        }
        ///Major rev of the IP.
        #[inline(always)]
        pub const fn set_majrev(&mut self, val: u8) {
            self.0 = (self.0 & !(0x0f << 4usize)) | (((val as u32) & 0x0f) << 4usize);
        }
        ///Instance Number within the device. This will be a parameter to the RTL for modules that can have multiple instances.
        #[must_use]
        #[inline(always)]
        pub const fn instnum(&self) -> u8 {
            let val = (self.0 >> 8usize) & 0x0f;
            val as u8
        }
        ///Instance Number within the device. This will be a parameter to the RTL for modules that can have multiple instances.
        #[inline(always)]
        pub const fn set_instnum(&mut self, val: u8) {
            self.0 = (self.0 & !(0x0f << 8usize)) | (((val as u32) & 0x0f) << 8usize);
        }
        ///Feature Set for the module *instance*.
        #[must_use]
        #[inline(always)]
        pub const fn featurever(&self) -> u8 {
            let val = (self.0 >> 12usize) & 0x0f;
            val as u8
        }
        ///Feature Set for the module *instance*.
        #[inline(always)]
        pub const fn set_featurever(&mut self, val: u8) {
            self.0 = (self.0 & !(0x0f << 12usize)) | (((val as u32) & 0x0f) << 12usize);
        }
        ///Module identification contains a unique peripheral identification number. The assignments are maintained in a central database for all of the platform modules to ensure uniqueness.
        #[must_use]
        #[inline(always)]
        pub const fn moduleid(&self) -> u16 {
            let val = (self.0 >> 16usize) & 0xffff;
            val as u16
        }
        ///Module identification contains a unique peripheral identification number. The assignments are maintained in a central database for all of the platform modules to ensure uniqueness.
        #[inline(always)]
        pub const fn set_moduleid(&mut self, val: u16) {
            self.0 = (self.0 & !(0xffff << 16usize))
                | (((val as u32) & 0xffff) << 16usize);
        }
    }
    impl Default for Desc {
        #[inline(always)]
        fn default() -> Desc {
            Desc(0)
        }
    }
    impl core::fmt::Debug for Desc {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Desc")
                .field("minrev", &self.minrev())
                .field("majrev", &self.majrev())
                .field("instnum", &self.instnum())
                .field("featurever", &self.featurever())
                .field("moduleid", &self.moduleid())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Desc {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f,
                "Desc {{ minrev: {=u8:?}, majrev: {=u8:?}, instnum: {=u8:?}, featurever: {=u8:?}, moduleid: {=u16:?} }}",
                self.minrev(), self.majrev(), self.instnum(), self.featurever(), self
                .moduleid()
            )
        }
    }
    ///Event Mode.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct EvtMode(pub u32);
    impl EvtMode {
        ///Event line mode select for event corresponding to \[IPSTANDARD.INT_EVENT\]\[0\].
        #[must_use]
        #[inline(always)]
        pub const fn int0_cfg(&self) -> super::vals::IntCfg {
            let val = (self.0 >> 0usize) & 0x03;
            super::vals::IntCfg::from_bits(val as u8)
        }
        ///Event line mode select for event corresponding to \[IPSTANDARD.INT_EVENT\]\[0\].
        #[inline(always)]
        pub const fn set_int0_cfg(&mut self, val: super::vals::IntCfg) {
            self.0 = (self.0 & !(0x03 << 0usize))
                | (((val.to_bits() as u32) & 0x03) << 0usize);
        }
    }
    impl Default for EvtMode {
        #[inline(always)]
        fn default() -> EvtMode {
            EvtMode(0)
        }
    }
    impl core::fmt::Debug for EvtMode {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("EvtMode").field("int0_cfg", &self.int0_cfg()).finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for EvtMode {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(f, "EvtMode {{ int0_cfg: {:?} }}", self.int0_cfg())
        }
    }
    ///Interrupt index.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Iidx(pub u32);
    impl Iidx {
        ///Module Interrupt Vector Value. This register provides the highest priority interrupt index. A read clears the corresponding interrupt flag in RIS and MISC.
        #[must_use]
        #[inline(always)]
        pub const fn stat(&self) -> super::vals::Stat {
            let val = (self.0 >> 0usize) & 0x1f;
            super::vals::Stat::from_bits(val as u8)
        }
        ///Module Interrupt Vector Value. This register provides the highest priority interrupt index. A read clears the corresponding interrupt flag in RIS and MISC.
        #[inline(always)]
        pub const fn set_stat(&mut self, val: super::vals::Stat) {
            self.0 = (self.0 & !(0x1f << 0usize))
                | (((val.to_bits() as u32) & 0x1f) << 0usize);
        }
    }
    impl Default for Iidx {
        #[inline(always)]
        fn default() -> Iidx {
            Iidx(0)
        }
    }
    impl core::fmt::Debug for Iidx {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Iidx").field("stat", &self.stat()).finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Iidx {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(f, "Iidx {{ stat: {:?} }}", self.stat())
        }
    }
    ///Interrupt clear.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Int(pub u32);
    impl Int {
        ///Interval Timer Interrupt.
        #[must_use]
        #[inline(always)]
        pub const fn inttim(&self) -> bool {
            let val = (self.0 >> 0usize) & 0x01;
            val != 0
        }
        ///Interval Timer Interrupt.
        #[inline(always)]
        pub const fn set_inttim(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize);
        }
    }
    impl Default for Int {
        #[inline(always)]
        fn default() -> Int {
            Int(0)
        }
    }
    impl core::fmt::Debug for Int {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Int").field("inttim", &self.inttim()).finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Int {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(f, "Int {{ inttim: {=bool:?} }}", self.inttim())
        }
    }
    ///Peripheral Debug Control.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Pdbgctl(pub u32);
    impl Pdbgctl {
        ///Free run control.
        #[must_use]
        #[inline(always)]
        pub const fn free(&self) -> bool {
            let val = (self.0 >> 0usize) & 0x01;
            val != 0
        }
        ///Free run control.
        #[inline(always)]
        pub const fn set_free(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize);
        }
    }
    impl Default for Pdbgctl {
        #[inline(always)]
        fn default() -> Pdbgctl {
            Pdbgctl(0)
        }
    }
    impl core::fmt::Debug for Pdbgctl {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Pdbgctl").field("free", &self.free()).finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Pdbgctl {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(f, "Pdbgctl {{ free: {=bool:?} }}", self.free())
        }
    }
    ///Power enable.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Pwren(pub u32);
    impl Pwren {
        ///Enable the power Note: For safety devices the power cannot be disabled once enabled.
        #[must_use]
        #[inline(always)]
        pub const fn enable(&self) -> bool {
            let val = (self.0 >> 0usize) & 0x01;
            val != 0
        }
        ///Enable the power Note: For safety devices the power cannot be disabled once enabled.
        #[inline(always)]
        pub const fn set_enable(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize);
        }
        ///KEY to allow Power State Change 26h = KEY to allow write access to this register
        #[must_use]
        #[inline(always)]
        pub const fn key(&self) -> super::vals::PwrenKey {
            let val = (self.0 >> 24usize) & 0xff;
            super::vals::PwrenKey::from_bits(val as u8)
        }
        ///KEY to allow Power State Change 26h = KEY to allow write access to this register
        #[inline(always)]
        pub const fn set_key(&mut self, val: super::vals::PwrenKey) {
            self.0 = (self.0 & !(0xff << 24usize))
                | (((val.to_bits() as u32) & 0xff) << 24usize);
        }
    }
    impl Default for Pwren {
        #[inline(always)]
        fn default() -> Pwren {
            Pwren(0)
        }
    }
    impl core::fmt::Debug for Pwren {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Pwren")
                .field("enable", &self.enable())
                .field("key", &self.key())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Pwren {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f, "Pwren {{ enable: {=bool:?}, key: {:?} }}", self.enable(), self.key()
            )
        }
    }
    ///Reset Control.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Rstctl(pub u32);
    impl Rstctl {
        ///Assert reset to the peripheral Note: For safety devices a watchdog reset by software is not possible.
        #[must_use]
        #[inline(always)]
        pub const fn resetassert(&self) -> bool {
            let val = (self.0 >> 0usize) & 0x01;
            val != 0
        }
        ///Assert reset to the peripheral Note: For safety devices a watchdog reset by software is not possible.
        #[inline(always)]
        pub const fn set_resetassert(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize);
        }
        ///Clear \[GPRCM.STAT.RESETSTKY\].
        #[must_use]
        #[inline(always)]
        pub const fn resetstkyclr(&self) -> bool {
            let val = (self.0 >> 1usize) & 0x01;
            val != 0
        }
        ///Clear \[GPRCM.STAT.RESETSTKY\].
        #[inline(always)]
        pub const fn set_resetstkyclr(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize);
        }
        ///Unlock key B1h = KEY to allow write access to this register
        #[must_use]
        #[inline(always)]
        pub const fn key(&self) -> super::vals::ResetKey {
            let val = (self.0 >> 24usize) & 0xff;
            super::vals::ResetKey::from_bits(val as u8)
        }
        ///Unlock key B1h = KEY to allow write access to this register
        #[inline(always)]
        pub const fn set_key(&mut self, val: super::vals::ResetKey) {
            self.0 = (self.0 & !(0xff << 24usize))
                | (((val.to_bits() as u32) & 0xff) << 24usize);
        }
    }
    impl Default for Rstctl {
        #[inline(always)]
        fn default() -> Rstctl {
            Rstctl(0)
        }
    }
    impl core::fmt::Debug for Rstctl {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Rstctl")
                .field("resetassert", &self.resetassert())
                .field("resetstkyclr", &self.resetstkyclr())
                .field("key", &self.key())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Rstctl {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f,
                "Rstctl {{ resetassert: {=bool:?}, resetstkyclr: {=bool:?}, key: {:?} }}",
                self.resetassert(), self.resetstkyclr(), self.key()
            )
        }
    }
    ///Status Register.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Stat(pub u32);
    impl Stat {
        ///This bit indicates, if the peripheral was reset, since this bit was cleared by RESETSTKYCLR in the RSTCTL register.
        #[must_use]
        #[inline(always)]
        pub const fn resetstky(&self) -> bool {
            let val = (self.0 >> 16usize) & 0x01;
            val != 0
        }
        ///This bit indicates, if the peripheral was reset, since this bit was cleared by RESETSTKYCLR in the RSTCTL register.
        #[inline(always)]
        pub const fn set_resetstky(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize);
        }
    }
    impl Default for Stat {
        #[inline(always)]
        fn default() -> Stat {
            Stat(0)
        }
    }
    impl core::fmt::Debug for Stat {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Stat").field("resetstky", &self.resetstky()).finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Stat {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(f, "Stat {{ resetstky: {=bool:?} }}", self.resetstky())
        }
    }
    ///Window Watchdog Timer Counter Reset Register.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Wwdtcntrst(pub u32);
    impl Wwdtcntrst {
        ///Window Watchdog Timer Counter Restart Writing 00A7h to this register restarts the WWDT Counter.
        #[must_use]
        #[inline(always)]
        pub const fn restart(&self) -> super::vals::WwdtcntrstRestart {
            let val = (self.0 >> 0usize) & 0xffff_ffff;
            super::vals::WwdtcntrstRestart::from_bits(val as u32)
        }
        ///Window Watchdog Timer Counter Restart Writing 00A7h to this register restarts the WWDT Counter.
        #[inline(always)]
        pub const fn set_restart(&mut self, val: super::vals::WwdtcntrstRestart) {
            self.0 = (self.0 & !(0xffff_ffff << 0usize))
                | (((val.to_bits() as u32) & 0xffff_ffff) << 0usize);
        }
    }
    impl Default for Wwdtcntrst {
        #[inline(always)]
        fn default() -> Wwdtcntrst {
            Wwdtcntrst(0)
        }
    }
    impl core::fmt::Debug for Wwdtcntrst {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Wwdtcntrst").field("restart", &self.restart()).finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Wwdtcntrst {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(f, "Wwdtcntrst {{ restart: {:?} }}", self.restart())
        }
    }
    ///Window Watchdog Timer Control Register 0.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Wwdtctl0(pub u32);
    impl Wwdtctl0 {
        ///Module Clock Divider, Divide the clock source by CLKDIV+1. Divider values from /1 to /8 are possible. The clock divider is currently 4 bits. Bit 4 has no effect and should always be written with 0.
        #[must_use]
        #[inline(always)]
        pub const fn clkdiv(&self) -> u8 {
            let val = (self.0 >> 0usize) & 0x07;
            val as u8
        }
        ///Module Clock Divider, Divide the clock source by CLKDIV+1. Divider values from /1 to /8 are possible. The clock divider is currently 4 bits. Bit 4 has no effect and should always be written with 0.
        #[inline(always)]
        pub const fn set_clkdiv(&mut self, val: u8) {
            self.0 = (self.0 & !(0x07 << 0usize)) | (((val as u32) & 0x07) << 0usize);
        }
        ///Timer Period of the WWDT. These bits select the total watchdog timer count.
        #[must_use]
        #[inline(always)]
        pub const fn per(&self) -> super::vals::Per {
            let val = (self.0 >> 4usize) & 0x07;
            super::vals::Per::from_bits(val as u8)
        }
        ///Timer Period of the WWDT. These bits select the total watchdog timer count.
        #[inline(always)]
        pub const fn set_per(&mut self, val: super::vals::Per) {
            self.0 = (self.0 & !(0x07 << 4usize))
                | (((val.to_bits() as u32) & 0x07) << 4usize);
        }
        ///Closed window period in percentage of the timer interval. WWDTCTL1.WINSEL determines the active window setting (WWDTCTL0.WINDOW0 or WWDTCTL0.WINDOW1).
        #[must_use]
        #[inline(always)]
        pub const fn window0(&self) -> super::vals::Window {
            let val = (self.0 >> 8usize) & 0x07;
            super::vals::Window::from_bits(val as u8)
        }
        ///Closed window period in percentage of the timer interval. WWDTCTL1.WINSEL determines the active window setting (WWDTCTL0.WINDOW0 or WWDTCTL0.WINDOW1).
        #[inline(always)]
        pub const fn set_window0(&mut self, val: super::vals::Window) {
            self.0 = (self.0 & !(0x07 << 8usize))
                | (((val.to_bits() as u32) & 0x07) << 8usize);
        }
        ///Closed window period in percentage of the timer interval. WWDTCTL1.WINSEL determines the active window setting (WWDTCTL0.WINDOW0 or WWDTCTL0.WINDOW1).
        #[must_use]
        #[inline(always)]
        pub const fn window1(&self) -> super::vals::Window {
            let val = (self.0 >> 12usize) & 0x07;
            super::vals::Window::from_bits(val as u8)
        }
        ///Closed window period in percentage of the timer interval. WWDTCTL1.WINSEL determines the active window setting (WWDTCTL0.WINDOW0 or WWDTCTL0.WINDOW1).
        #[inline(always)]
        pub const fn set_window1(&mut self, val: super::vals::Window) {
            self.0 = (self.0 & !(0x07 << 12usize))
                | (((val.to_bits() as u32) & 0x07) << 12usize);
        }
        ///Window Watchdog Timer Mode.
        #[must_use]
        #[inline(always)]
        pub const fn mode(&self) -> super::vals::Mode {
            let val = (self.0 >> 16usize) & 0x01;
            super::vals::Mode::from_bits(val as u8)
        }
        ///Window Watchdog Timer Mode.
        #[inline(always)]
        pub const fn set_mode(&mut self, val: super::vals::Mode) {
            self.0 = (self.0 & !(0x01 << 16usize))
                | (((val.to_bits() as u32) & 0x01) << 16usize);
        }
        ///Stop In Sleep Mode. The functionality of this bit requires that POLICY.HWCEN = 0. If POLICY.HWCEN = 1 the WWDT resets during sleep and needs re-configuration. Note: This bit has no effect for the global Window Watchdog as Sleep Mode is not supported.
        #[must_use]
        #[inline(always)]
        pub const fn stism(&self) -> super::vals::Stism {
            let val = (self.0 >> 17usize) & 0x01;
            super::vals::Stism::from_bits(val as u8)
        }
        ///Stop In Sleep Mode. The functionality of this bit requires that POLICY.HWCEN = 0. If POLICY.HWCEN = 1 the WWDT resets during sleep and needs re-configuration. Note: This bit has no effect for the global Window Watchdog as Sleep Mode is not supported.
        #[inline(always)]
        pub const fn set_stism(&mut self, val: super::vals::Stism) {
            self.0 = (self.0 & !(0x01 << 17usize))
                | (((val.to_bits() as u32) & 0x01) << 17usize);
        }
        ///KEY to allow write access to WWDTCTL0 = C9h.
        #[must_use]
        #[inline(always)]
        pub const fn key(&self) -> super::vals::Wwdtctl0Key {
            let val = (self.0 >> 24usize) & 0xff;
            super::vals::Wwdtctl0Key::from_bits(val as u8)
        }
        ///KEY to allow write access to WWDTCTL0 = C9h.
        #[inline(always)]
        pub const fn set_key(&mut self, val: super::vals::Wwdtctl0Key) {
            self.0 = (self.0 & !(0xff << 24usize))
                | (((val.to_bits() as u32) & 0xff) << 24usize);
        }
    }
    impl Default for Wwdtctl0 {
        #[inline(always)]
        fn default() -> Wwdtctl0 {
            Wwdtctl0(0)
        }
    }
    impl core::fmt::Debug for Wwdtctl0 {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Wwdtctl0")
                .field("clkdiv", &self.clkdiv())
                .field("per", &self.per())
                .field("window0", &self.window0())
                .field("window1", &self.window1())
                .field("mode", &self.mode())
                .field("stism", &self.stism())
                .field("key", &self.key())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Wwdtctl0 {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f,
                "Wwdtctl0 {{ clkdiv: {=u8:?}, per: {:?}, window0: {:?}, window1: {:?}, mode: {:?}, stism: {:?}, key: {:?} }}",
                self.clkdiv(), self.per(), self.window0(), self.window1(), self.mode(),
                self.stism(), self.key()
            )
        }
    }
    ///Window Watchdog Timer Control Register 0.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Wwdtctl1(pub u32);
    impl Wwdtctl1 {
        ///Close Window Select.
        #[must_use]
        #[inline(always)]
        pub const fn winsel(&self) -> super::vals::Winsel {
            let val = (self.0 >> 0usize) & 0x01;
            super::vals::Winsel::from_bits(val as u8)
        }
        ///Close Window Select.
        #[inline(always)]
        pub const fn set_winsel(&mut self, val: super::vals::Winsel) {
            self.0 = (self.0 & !(0x01 << 0usize))
                | (((val.to_bits() as u32) & 0x01) << 0usize);
        }
        ///KEY to allow write access to WWDTCTL1 = BEh.
        #[must_use]
        #[inline(always)]
        pub const fn key(&self) -> super::vals::Wwdtctl1Key {
            let val = (self.0 >> 24usize) & 0xff;
            super::vals::Wwdtctl1Key::from_bits(val as u8)
        }
        ///KEY to allow write access to WWDTCTL1 = BEh.
        #[inline(always)]
        pub const fn set_key(&mut self, val: super::vals::Wwdtctl1Key) {
            self.0 = (self.0 & !(0xff << 24usize))
                | (((val.to_bits() as u32) & 0xff) << 24usize);
        }
    }
    impl Default for Wwdtctl1 {
        #[inline(always)]
        fn default() -> Wwdtctl1 {
            Wwdtctl1(0)
        }
    }
    impl core::fmt::Debug for Wwdtctl1 {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Wwdtctl1")
                .field("winsel", &self.winsel())
                .field("key", &self.key())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Wwdtctl1 {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f, "Wwdtctl1 {{ winsel: {:?}, key: {:?} }}", self.winsel(), self.key()
            )
        }
    }
    ///Window Watchdog Timer Status Register.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Wwdtstat(pub u32);
    impl Wwdtstat {
        ///Watchdog running status flag.
        #[must_use]
        #[inline(always)]
        pub const fn run(&self) -> bool {
            let val = (self.0 >> 0usize) & 0x01;
            val != 0
        }
        ///Watchdog running status flag.
        #[inline(always)]
        pub const fn set_run(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize);
        }
    }
    impl Default for Wwdtstat {
        #[inline(always)]
        fn default() -> Wwdtstat {
            Wwdtstat(0)
        }
    }
    impl core::fmt::Debug for Wwdtstat {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Wwdtstat").field("run", &self.run()).finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Wwdtstat {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(f, "Wwdtstat {{ run: {=bool:?} }}", self.run())
        }
    }
}
pub mod vals {
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum IntCfg {
        ///The interrupt or event line is disabled.
        Disable = 0x0,
        ///The interrupt or event line is in software mode. Software must clear the RIS.
        Software = 0x01,
        ///The interrupt or event line is in hardware mode. The hardware (another module) clears automatically the associated RIS flag.
        Hardware = 0x02,
        _RESERVED_3 = 0x03,
    }
    impl IntCfg {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> IntCfg {
            unsafe { core::mem::transmute(val & 0x03) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for IntCfg {
        #[inline(always)]
        fn from(val: u8) -> IntCfg {
            IntCfg::from_bits(val)
        }
    }
    impl From<IntCfg> for u8 {
        #[inline(always)]
        fn from(val: IntCfg) -> u8 {
            IntCfg::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum Mode {
        ///Window Watchdog Timer Mode. The WWDT will generate a error signal to the ESM when following conditions occur: - Timer Expiration (Timeout) - Reset WWDT during the active window closed period - Keyword violation.
        Window = 0x0,
        ///Interval Timer Mode. The WWDT acts as an interval timer. It generates an interrupt on timeout.
        Interval = 0x01,
    }
    impl Mode {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Mode {
            unsafe { core::mem::transmute(val & 0x01) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Mode {
        #[inline(always)]
        fn from(val: u8) -> Mode {
            Mode::from_bits(val)
        }
    }
    impl From<Mode> for u8 {
        #[inline(always)]
        fn from(val: Mode) -> u8 {
            Mode::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum Per {
        ///Total timer count is 2^25.
        En25 = 0x0,
        ///Total timer count is 2^21.
        En21 = 0x01,
        ///Total timer count is 2^18.
        En18 = 0x02,
        ///Total timer count is 2^15.
        En15 = 0x03,
        ///Total timer count is 2^12 (default).
        En12 = 0x04,
        ///Total timer count is 2^10.
        En10 = 0x05,
        ///Total timer count is 2^8.
        En8 = 0x06,
        ///Total timer count is 2^6.
        En6 = 0x07,
    }
    impl Per {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Per {
            unsafe { core::mem::transmute(val & 0x07) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Per {
        #[inline(always)]
        fn from(val: u8) -> Per {
            Per::from_bits(val)
        }
    }
    impl From<Per> for u8 {
        #[inline(always)]
        fn from(val: Per) -> u8 {
            Per::to_bits(val)
        }
    }
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
    pub struct PwrenKey(u8);
    impl PwrenKey {
        pub const Key: Self = Self(0x26);
    }
    impl PwrenKey {
        pub const fn from_bits(val: u8) -> PwrenKey {
            Self(val & 0xff)
        }
        pub const fn to_bits(self) -> u8 {
            self.0
        }
    }
    impl core::fmt::Debug for PwrenKey {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            match self.0 {
                0x26 => f.write_str("Key"),
                other => core::write!(f, "0x{:02X}", other),
            }
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for PwrenKey {
        fn format(&self, f: defmt::Formatter) {
            match self.0 {
                0x26 => defmt::write!(f, "Key"),
                other => defmt::write!(f, "0x{:02X}", other),
            }
        }
    }
    impl From<u8> for PwrenKey {
        #[inline(always)]
        fn from(val: u8) -> PwrenKey {
            PwrenKey::from_bits(val)
        }
    }
    impl From<PwrenKey> for u8 {
        #[inline(always)]
        fn from(val: PwrenKey) -> u8 {
            PwrenKey::to_bits(val)
        }
    }
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
    pub struct ResetKey(u8);
    impl ResetKey {
        pub const Key: Self = Self(0xb1);
    }
    impl ResetKey {
        pub const fn from_bits(val: u8) -> ResetKey {
            Self(val & 0xff)
        }
        pub const fn to_bits(self) -> u8 {
            self.0
        }
    }
    impl core::fmt::Debug for ResetKey {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            match self.0 {
                0xb1 => f.write_str("Key"),
                other => core::write!(f, "0x{:02X}", other),
            }
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for ResetKey {
        fn format(&self, f: defmt::Formatter) {
            match self.0 {
                0xb1 => defmt::write!(f, "Key"),
                other => defmt::write!(f, "0x{:02X}", other),
            }
        }
    }
    impl From<u8> for ResetKey {
        #[inline(always)]
        fn from(val: u8) -> ResetKey {
            ResetKey::from_bits(val)
        }
    }
    impl From<ResetKey> for u8 {
        #[inline(always)]
        fn from(val: ResetKey) -> u8 {
            ResetKey::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum Stat {
        ///No interrupt pending.
        NoIntr = 0x0,
        ///Interval Timer Interrupt; Interrupt Flag: INTTIM; Interrupt Priority: Highest.
        Inttim = 0x01,
        _RESERVED_2 = 0x02,
        _RESERVED_3 = 0x03,
        _RESERVED_4 = 0x04,
        _RESERVED_5 = 0x05,
        _RESERVED_6 = 0x06,
        _RESERVED_7 = 0x07,
        _RESERVED_8 = 0x08,
        _RESERVED_9 = 0x09,
        _RESERVED_a = 0x0a,
        _RESERVED_b = 0x0b,
        _RESERVED_c = 0x0c,
        _RESERVED_d = 0x0d,
        _RESERVED_e = 0x0e,
        _RESERVED_f = 0x0f,
        _RESERVED_10 = 0x10,
        _RESERVED_11 = 0x11,
        _RESERVED_12 = 0x12,
        _RESERVED_13 = 0x13,
        _RESERVED_14 = 0x14,
        _RESERVED_15 = 0x15,
        _RESERVED_16 = 0x16,
        _RESERVED_17 = 0x17,
        _RESERVED_18 = 0x18,
        _RESERVED_19 = 0x19,
        _RESERVED_1a = 0x1a,
        _RESERVED_1b = 0x1b,
        _RESERVED_1c = 0x1c,
        _RESERVED_1d = 0x1d,
        _RESERVED_1e = 0x1e,
        _RESERVED_1f = 0x1f,
    }
    impl Stat {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Stat {
            unsafe { core::mem::transmute(val & 0x1f) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Stat {
        #[inline(always)]
        fn from(val: u8) -> Stat {
            Stat::from_bits(val)
        }
    }
    impl From<Stat> for u8 {
        #[inline(always)]
        fn from(val: Stat) -> u8 {
            Stat::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum Stism {
        ///The WWDT continues to function in Sleep mode.
        Cont = 0x0,
        ///The WWDT stops in Sleep mode and resumes where it was stopped after wakeup.
        Stop = 0x01,
    }
    impl Stism {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Stism {
            unsafe { core::mem::transmute(val & 0x01) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Stism {
        #[inline(always)]
        fn from(val: u8) -> Stism {
            Stism::from_bits(val)
        }
    }
    impl From<Stism> for u8 {
        #[inline(always)]
        fn from(val: Stism) -> u8 {
            Stism::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum Window {
        ///0% (No closed Window).
        Size0 = 0x0,
        ///12.50% of the total timer period is closed window.
        Size12 = 0x01,
        ///18.75% of the total timer period is closed window.
        Size18 = 0x02,
        ///25% of the total timer period is closed window.
        Size25 = 0x03,
        ///50% of the total timer period is closed window.
        Size50 = 0x04,
        ///75% of the total timer period is closed window.
        Size75 = 0x05,
        ///81.25% of the total timer period is closed window.
        Size81 = 0x06,
        ///87.50% of the total timer period is closed window.
        Size87 = 0x07,
    }
    impl Window {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Window {
            unsafe { core::mem::transmute(val & 0x07) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Window {
        #[inline(always)]
        fn from(val: u8) -> Window {
            Window::from_bits(val)
        }
    }
    impl From<Window> for u8 {
        #[inline(always)]
        fn from(val: Window) -> u8 {
            Window::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum Winsel {
        ///In window mode field WINDOW0 of WDDTCTL0 defines the closed window size.
        Win0 = 0x0,
        ///In window mode field WINDOW1 of WDDTCTL0 defines the closed window size.
        Win1 = 0x01,
    }
    impl Winsel {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Winsel {
            unsafe { core::mem::transmute(val & 0x01) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Winsel {
        #[inline(always)]
        fn from(val: u8) -> Winsel {
            Winsel::from_bits(val)
        }
    }
    impl From<Winsel> for u8 {
        #[inline(always)]
        fn from(val: Winsel) -> u8 {
            Winsel::to_bits(val)
        }
    }
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
    pub struct WwdtcntrstRestart(u32);
    impl WwdtcntrstRestart {
        pub const Restart: Self = Self(0xa7);
    }
    impl WwdtcntrstRestart {
        pub const fn from_bits(val: u32) -> WwdtcntrstRestart {
            Self(val & 0xffff_ffff)
        }
        pub const fn to_bits(self) -> u32 {
            self.0
        }
    }
    impl core::fmt::Debug for WwdtcntrstRestart {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            match self.0 {
                0xa7 => f.write_str("Restart"),
                other => core::write!(f, "0x{:02X}", other),
            }
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for WwdtcntrstRestart {
        fn format(&self, f: defmt::Formatter) {
            match self.0 {
                0xa7 => defmt::write!(f, "Restart"),
                other => defmt::write!(f, "0x{:02X}", other),
            }
        }
    }
    impl From<u32> for WwdtcntrstRestart {
        #[inline(always)]
        fn from(val: u32) -> WwdtcntrstRestart {
            WwdtcntrstRestart::from_bits(val)
        }
    }
    impl From<WwdtcntrstRestart> for u32 {
        #[inline(always)]
        fn from(val: WwdtcntrstRestart) -> u32 {
            WwdtcntrstRestart::to_bits(val)
        }
    }
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
    pub struct Wwdtctl0Key(u8);
    impl Wwdtctl0Key {
        pub const Key: Self = Self(0xc9);
    }
    impl Wwdtctl0Key {
        pub const fn from_bits(val: u8) -> Wwdtctl0Key {
            Self(val & 0xff)
        }
        pub const fn to_bits(self) -> u8 {
            self.0
        }
    }
    impl core::fmt::Debug for Wwdtctl0Key {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            match self.0 {
                0xc9 => f.write_str("Key"),
                other => core::write!(f, "0x{:02X}", other),
            }
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Wwdtctl0Key {
        fn format(&self, f: defmt::Formatter) {
            match self.0 {
                0xc9 => defmt::write!(f, "Key"),
                other => defmt::write!(f, "0x{:02X}", other),
            }
        }
    }
    impl From<u8> for Wwdtctl0Key {
        #[inline(always)]
        fn from(val: u8) -> Wwdtctl0Key {
            Wwdtctl0Key::from_bits(val)
        }
    }
    impl From<Wwdtctl0Key> for u8 {
        #[inline(always)]
        fn from(val: Wwdtctl0Key) -> u8 {
            Wwdtctl0Key::to_bits(val)
        }
    }
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
    pub struct Wwdtctl1Key(u8);
    impl Wwdtctl1Key {
        pub const Key: Self = Self(0xbe);
    }
    impl Wwdtctl1Key {
        pub const fn from_bits(val: u8) -> Wwdtctl1Key {
            Self(val & 0xff)
        }
        pub const fn to_bits(self) -> u8 {
            self.0
        }
    }
    impl core::fmt::Debug for Wwdtctl1Key {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            match self.0 {
                0xbe => f.write_str("Key"),
                other => core::write!(f, "0x{:02X}", other),
            }
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Wwdtctl1Key {
        fn format(&self, f: defmt::Formatter) {
            match self.0 {
                0xbe => defmt::write!(f, "Key"),
                other => defmt::write!(f, "0x{:02X}", other),
            }
        }
    }
    impl From<u8> for Wwdtctl1Key {
        #[inline(always)]
        fn from(val: u8) -> Wwdtctl1Key {
            Wwdtctl1Key::from_bits(val)
        }
    }
    impl From<Wwdtctl1Key> for u8 {
        #[inline(always)]
        fn from(val: Wwdtctl1Key) -> u8 {
            Wwdtctl1Key::to_bits(val)
        }
    }
}
