// This file is autogenerated by mspm0-metapac-gen: do not edit by hand.

include!("../metadata_0016.rs");
pub static METADATA: Metadata = Metadata {
    name: "mspm0g1519rhb",
    family: "mspm0g151x",
    peripherals: PERIPHERALS,
    pins: PINS,
    interrupts: INTERRUPTS,
    dma_channels: DMA_CHANNELS,
};
