// This file is autogenerated by mspm0-metapac-gen: do not edit by hand.
pub static METADATA: Metadata = Metadata {
    name: "mspm0l222x",
    peripherals: &[
        Peripheral {
            name: "CPUSS",
            kind: "cpuss",
            pins: &[],
        },
        Peripheral {
            name: "GPIOA",
            kind: "gpio",
            pins: &[],
        },
        Peripheral {
            name: "GPIOB",
            kind: "gpio",
            pins: &[],
        },
        Peripheral {
            name: "GPIOC",
            kind: "gpio",
            pins: &[],
        },
        Peripheral {
            name: "IOMUX",
            kind: "iomux",
            pins: &[],
        },
        Peripheral {
            name: "TIMA0",
            kind: "tim",
            pins: &[],
        },
        Peripheral {
            name: "TIMG0",
            kind: "tim",
            pins: &[],
        },
        Peripheral {
            name: "TIMG12",
            kind: "tim",
            pins: &[],
        },
        Peripheral {
            name: "TIMG4",
            kind: "tim",
            pins: &[],
        },
        Peripheral {
            name: "TIMG5",
            kind: "tim",
            pins: &[],
        },
        Peripheral {
            name: "TIMG8",
            kind: "tim",
            pins: &[],
        },
        Peripheral {
            name: "UART0",
            kind: "uart",
            pins: &[],
        },
        Peripheral {
            name: "UART1",
            kind: "uart",
            pins: &[],
        },
        Peripheral {
            name: "UART2",
            kind: "uart",
            pins: &[],
        },
        Peripheral {
            name: "UART3",
            kind: "uart",
            pins: &[],
        },
        Peripheral {
            name: "UART4",
            kind: "uart",
            pins: &[],
        },
    ],
    pincm_mappings: &[
        PinCmMapping {
            pin: "PA0",
            pincm: 1,
        },
        PinCmMapping {
            pin: "PA1",
            pincm: 2,
        },
        PinCmMapping {
            pin: "PA10",
            pincm: 25,
        },
        PinCmMapping {
            pin: "PA11",
            pincm: 26,
        },
        PinCmMapping {
            pin: "PA12",
            pincm: 38,
        },
        PinCmMapping {
            pin: "PA13",
            pincm: 39,
        },
        PinCmMapping {
            pin: "PA14",
            pincm: 40,
        },
        PinCmMapping {
            pin: "PA15",
            pincm: 41,
        },
        PinCmMapping {
            pin: "PA16",
            pincm: 42,
        },
        PinCmMapping {
            pin: "PA17",
            pincm: 49,
        },
        PinCmMapping {
            pin: "PA18",
            pincm: 50,
        },
        PinCmMapping {
            pin: "PA19",
            pincm: 51,
        },
        PinCmMapping {
            pin: "PA2",
            pincm: 7,
        },
        PinCmMapping {
            pin: "PA20",
            pincm: 52,
        },
        PinCmMapping {
            pin: "PA21",
            pincm: 56,
        },
        PinCmMapping {
            pin: "PA22",
            pincm: 57,
        },
        PinCmMapping {
            pin: "PA23",
            pincm: 67,
        },
        PinCmMapping {
            pin: "PA24",
            pincm: 68,
        },
        PinCmMapping {
            pin: "PA25",
            pincm: 69,
        },
        PinCmMapping {
            pin: "PA26",
            pincm: 73,
        },
        PinCmMapping {
            pin: "PA27",
            pincm: 74,
        },
        PinCmMapping {
            pin: "PA28",
            pincm: 3,
        },
        PinCmMapping {
            pin: "PA29",
            pincm: 4,
        },
        PinCmMapping {
            pin: "PA3",
            pincm: 8,
        },
        PinCmMapping {
            pin: "PA30",
            pincm: 5,
        },
        PinCmMapping {
            pin: "PA31",
            pincm: 6,
        },
        PinCmMapping {
            pin: "PA4",
            pincm: 9,
        },
        PinCmMapping {
            pin: "PA5",
            pincm: 10,
        },
        PinCmMapping {
            pin: "PA6",
            pincm: 11,
        },
        PinCmMapping {
            pin: "PA7",
            pincm: 14,
        },
        PinCmMapping {
            pin: "PA8",
            pincm: 19,
        },
        PinCmMapping {
            pin: "PA9",
            pincm: 20,
        },
        PinCmMapping {
            pin: "PB0",
            pincm: 12,
        },
        PinCmMapping {
            pin: "PB1",
            pincm: 13,
        },
        PinCmMapping {
            pin: "PB10",
            pincm: 31,
        },
        PinCmMapping {
            pin: "PB11",
            pincm: 32,
        },
        PinCmMapping {
            pin: "PB12",
            pincm: 33,
        },
        PinCmMapping {
            pin: "PB13",
            pincm: 34,
        },
        PinCmMapping {
            pin: "PB14",
            pincm: 35,
        },
        PinCmMapping {
            pin: "PB15",
            pincm: 36,
        },
        PinCmMapping {
            pin: "PB16",
            pincm: 37,
        },
        PinCmMapping {
            pin: "PB17",
            pincm: 53,
        },
        PinCmMapping {
            pin: "PB18",
            pincm: 54,
        },
        PinCmMapping {
            pin: "PB19",
            pincm: 55,
        },
        PinCmMapping {
            pin: "PB2",
            pincm: 15,
        },
        PinCmMapping {
            pin: "PB20",
            pincm: 62,
        },
        PinCmMapping {
            pin: "PB21",
            pincm: 63,
        },
        PinCmMapping {
            pin: "PB22",
            pincm: 64,
        },
        PinCmMapping {
            pin: "PB23",
            pincm: 65,
        },
        PinCmMapping {
            pin: "PB24",
            pincm: 66,
        },
        PinCmMapping {
            pin: "PB25",
            pincm: 70,
        },
        PinCmMapping {
            pin: "PB26",
            pincm: 71,
        },
        PinCmMapping {
            pin: "PB27",
            pincm: 72,
        },
        PinCmMapping {
            pin: "PB28",
            pincm: 21,
        },
        PinCmMapping {
            pin: "PB29",
            pincm: 22,
        },
        PinCmMapping {
            pin: "PB3",
            pincm: 16,
        },
        PinCmMapping {
            pin: "PB30",
            pincm: 23,
        },
        PinCmMapping {
            pin: "PB31",
            pincm: 24,
        },
        PinCmMapping {
            pin: "PB4",
            pincm: 17,
        },
        PinCmMapping {
            pin: "PB5",
            pincm: 18,
        },
        PinCmMapping {
            pin: "PB6",
            pincm: 27,
        },
        PinCmMapping {
            pin: "PB7",
            pincm: 28,
        },
        PinCmMapping {
            pin: "PB8",
            pincm: 29,
        },
        PinCmMapping {
            pin: "PB9",
            pincm: 30,
        },
        PinCmMapping {
            pin: "PC0",
            pincm: 43,
        },
        PinCmMapping {
            pin: "PC1",
            pincm: 44,
        },
        PinCmMapping {
            pin: "PC2",
            pincm: 45,
        },
        PinCmMapping {
            pin: "PC3",
            pincm: 46,
        },
        PinCmMapping {
            pin: "PC4",
            pincm: 47,
        },
        PinCmMapping {
            pin: "PC5",
            pincm: 48,
        },
        PinCmMapping {
            pin: "PC6",
            pincm: 58,
        },
        PinCmMapping {
            pin: "PC7",
            pincm: 59,
        },
        PinCmMapping {
            pin: "PC8",
            pincm: 60,
        },
        PinCmMapping {
            pin: "PC9",
            pincm: 61,
        },
    ],
    interrupts: &[
        Interrupt {
            name: "GROUP0",
            number: 0,
        },
        Interrupt {
            name: "GROUP1",
            number: 1,
        },
        Interrupt {
            name: "TIMG12",
            number: 2,
        },
        Interrupt {
            name: "UART4",
            number: 3,
        },
        Interrupt {
            name: "ADC0",
            number: 4,
        },
        Interrupt {
            name: "SPI0",
            number: 9,
        },
        Interrupt {
            name: "SPI1",
            number: 10,
        },
        Interrupt {
            name: "UART2",
            number: 13,
        },
        Interrupt {
            name: "UART3",
            number: 14,
        },
        Interrupt {
            name: "UART0",
            number: 15,
        },
        Interrupt {
            name: "UART1",
            number: 16,
        },
        Interrupt {
            name: "TIMA0",
            number: 18,
        },
        Interrupt {
            name: "TIMG8",
            number: 20,
        },
        Interrupt {
            name: "TIMG0",
            number: 21,
        },
        Interrupt {
            name: "TIMG4",
            number: 22,
        },
        Interrupt {
            name: "TIMG5",
            number: 23,
        },
        Interrupt {
            name: "I2C0",
            number: 24,
        },
        Interrupt {
            name: "I2C1",
            number: 25,
        },
        Interrupt {
            name: "I2C2",
            number: 26,
        },
        Interrupt {
            name: "AESADV",
            number: 28,
        },
        Interrupt {
            name: "LCD",
            number: 29,
        },
        Interrupt {
            name: "GROUP30",
            number: 30,
        },
        Interrupt {
            name: "DMA",
            number: 31,
        },
    ],
};
