// This file is autogenerated by mspm0-metapac-gen: do not edit by hand.

include!("../metadata_0033.rs");
pub static METADATA: Metadata = Metadata {
    name: "mspm0l1106rtr",
    family: "mspm0l110x",
    peripherals: PERIPHERALS,
    pins: PINS,
    interrupts: INTERRUPTS,
    dma_channels: DMA_CHANNELS,
};
