// This file is autogenerated by mspm0-metapac-gen: do not edit by hand.

include!("../metadata_0009.rs");
pub static METADATA: Metadata = Metadata {
    name: "mspm0g1106pm",
    family: "mspm0g110x",
    peripherals: PERIPHERALS,
    pins: PINS,
    interrupts: INTERRUPTS,
    interrupt_groups: INTERRUPT_GROUPS,
    dma_channels: DMA_CHANNELS,
};
