// This file is autogenerated by mspm0-metapac-gen: do not edit by hand.

include!("../metadata_0011.rs");
pub static METADATA: Metadata = Metadata {
    name: "mspm0c1106ruk",
    family: "mspm0c1105_c1106",
    peripherals: PERIPHERALS,
    pins: PINS,
    interrupts: INTERRUPTS,
    interrupt_groups: INTERRUPT_GROUPS,
    dma_channels: DMA_CHANNELS,
    adc_memctl: 12,
    adc_vrsel: 3,
};
