// This file is autogenerated by mspm0-metapac-gen: do not edit by hand.

include!("../metadata_0060.rs");
pub static METADATA: Metadata = Metadata {
    name: "msps003f4pw20",
    family: "msps003fx",
    peripherals: PERIPHERALS,
    pins: PINS,
    interrupts: INTERRUPTS,
    interrupt_groups: INTERRUPT_GROUPS,
    dma_channels: DMA_CHANNELS,
    adc_memctl: 4,
    adc_vrsel: 3,
};
