// This file is autogenerated by mspm0-metapac-gen: do not edit by hand.

include!("../metadata_0013.rs");
pub static METADATA: Metadata = Metadata {
    name: "mspm0g1506rgz",
    family: "mspm0g150x",
    peripherals: PERIPHERALS,
    pins: PINS,
    interrupts: INTERRUPTS,
    interrupt_groups: INTERRUPT_GROUPS,
    dma_channels: DMA_CHANNELS,
};
