// This file is autogenerated by mspm0-metapac-gen: do not edit by hand.

include!("../metadata_0049.rs");
pub static METADATA: Metadata = Metadata {
    name: "mspm0l2228pt",
    family: "mspm0l222x",
    peripherals: PERIPHERALS,
    pins: PINS,
    interrupts: INTERRUPTS,
    dma_channels: DMA_CHANNELS,
};
