// This file is autogenerated by mspm0-metapac-gen: do not edit by hand.

include!("../metadata_0052.rs");
pub static METADATA: Metadata = Metadata {
    name: "msps003f3pw20",
    family: "msps003fx",
    peripherals: PERIPHERALS,
    pins: PINS,
    interrupts: INTERRUPTS,
    interrupt_groups: INTERRUPT_GROUPS,
    dma_channels: DMA_CHANNELS,
};
